import { useEffect } from 'react';
import { Howl } from 'howler';
import { useSettingsStore } from '../store/settingsStore';
import type { ZoneKind } from '../content/zones';
import type { SeaArea } from '../content/boat';

/**
 * The game's audio engine (Howler.js). Two responsibilities: fire one-shot
 * **sound effects** (`sfx`) and play looping **background music** that follows
 * the current screen (`useScreenMusic`). Both honour the device settings —
 * audio is off by default, so every call here is a silent no-op until the
 * player enables Music / Sound in the menu.
 *
 * Files live in `public/audio/16bit/` (see `public/audio/README.md`). Load
 * errors are swallowed, so a missing file never breaks gameplay.
 */

export type SfxName =
  | 'correct'
  | 'wrong'
  | 'attack'
  | 'hit'
  | 'gate'
  | 'chest'
  | 'levelup'
  | 'victory'
  | 'select'
  // Battle (spells, defending, damage, Ember)
  | 'impact'
  | 'enemyAttack'
  | 'spell'
  | 'heal'
  | 'guard'
  | 'block'
  | 'shatter'
  | 'roar'
  | 'pair'
  | 'swap'
  | 'charge'
  | 'streak';

export type MusicTrack =
  | 'title'
  | 'overworld'
  | 'town'
  | 'cave'
  | 'shrine'
  | 'sailing'
  | 'shallows'
  | 'fogbank'
  | 'spire'
  | 'spireArchive'
  | 'spireThicket'
  | 'spireStars'
  | 'spireEngine'
  | 'finalBoss'
  | 'battle'
  | 'boss'
  | 'victory';

/**
 * The 16-bit chiptune set generated by `tools/assets/audio.py`
 * (`public/audio/16bit/`). Any Howler-supported file works — just change the
 * path here. The earlier player-supplied mp3s are still in `public/audio/` if
 * you want to swap a track back.
 */
export const SFX_SOURCES: Record<SfxName, string> = {
  hit: '/audio/16bit/sfx/hit.mp3', // player takes damage in battle
  wrong: '/audio/16bit/sfx/wrong.mp3', // a question answered incorrectly
  victory: '/audio/16bit/sfx/victory.mp3', // a battle is won (fanfare jingle)
  levelup: '/audio/16bit/sfx/levelup.mp3', // the level-up / choose-a-perk modal
  correct: '/audio/16bit/sfx/correct.mp3',
  attack: '/audio/16bit/sfx/attack.mp3',
  gate: '/audio/16bit/sfx/gate.mp3',
  chest: '/audio/16bit/sfx/chest.mp3',
  select: '/audio/16bit/sfx/select.mp3',
  impact: '/audio/16bit/sfx/impact.mp3', // an enemy takes damage
  enemyAttack: '/audio/16bit/sfx/enemyAttack.mp3', // the enemy lunges
  spell: '/audio/16bit/sfx/spell.mp3', // a spell is cast (landed)
  heal: '/audio/16bit/sfx/heal.mp3', // HP restored (Mend, potion, a healer enemy)
  guard: '/audio/16bit/sfx/guard.mp3', // a guard / shield is raised
  block: '/audio/16bit/sfx/block.mp3', // an enemy hit is fully blocked
  shatter: '/audio/16bit/sfx/shatter.mp3', // a shielded enemy's shield breaks
  roar: '/audio/16bit/sfx/roar.mp3', // Ember attacks
  pair: '/audio/16bit/sfx/pair.mp3', // a hero + companion Pair Attack
  swap: '/audio/16bit/sfx/swap.mp3', // a companion swaps in
  charge: '/audio/16bit/sfx/charge.mp3', // an enemy gathers power (telegraphed blow)
  streak: '/audio/16bit/sfx/streak.mp3', // correct answers in a row
};

export const MUSIC_SOURCES: Record<MusicTrack, string> = {
  overworld: '/audio/16bit/music/overworld.mp3', // the overworld + open fields
  town: '/audio/16bit/music/town.mp3', // towns (#75 Phase 1)
  cave: '/audio/16bit/music/cave.mp3', // caves and dungeons
  shrine: '/audio/16bit/music/shrine.mp3', // shrines
  // The sea (#75 item 14): one loop per sea area (`SEA_TRACK`).
  sailing: '/audio/16bit/music/sailing.mp3', // a shanty: sailing Dawnreach's waters
  shallows: '/audio/16bit/music/shallows.mp3', // the Silver Shallows, afloat or on its islets
  fogbank: '/audio/16bit/music/fogbank.mp3', // misty: near the Great Fogbank
  spire: '/audio/16bit/music/spire.mp3', // the Spire's entrance + intro
  // One spooky loop per Spire floor (#74); the throne floor uses finalBoss.
  spireArchive: '/audio/16bit/music/spireArchive.mp3',
  spireThicket: '/audio/16bit/music/spireThicket.mp3',
  spireStars: '/audio/16bit/music/spireStars.mp3',
  spireEngine: '/audio/16bit/music/spireEngine.mp3',
  finalBoss: '/audio/16bit/music/finalBoss.mp3', // the Umbra fight (Spire boss floor)
  battle: '/audio/16bit/music/battle.mp3', // regular battles
  boss: '/audio/16bit/music/boss.mp3', // area bosses (Fiends, wardens)
  title: '/audio/16bit/music/title.mp3', // menu screens
  victory: '/audio/16bit/music/victory.mp3', // looping victory theme — unused; the win uses the sfx jingle
};

const FADE_MS = 600;

// Lazily-built, cached Howls — one per registered source, reused across plays.
const sfxCache = new Map<SfxName, Howl>();
const musicCache = new Map<MusicTrack, Howl>();

function getSfx(name: SfxName): Howl | null {
  let howl = sfxCache.get(name);
  if (!howl) {
    try {
      howl = new Howl({ src: [SFX_SOURCES[name]], preload: false, volume: 1 });
      // A missing/undecodable file must never throw into gameplay.
      howl.on('loaderror', () => {});
      howl.on('playerror', () => {});
      sfxCache.set(name, howl);
    } catch {
      return null;
    }
  }
  return howl;
}

function getMusic(track: MusicTrack): Howl | null {
  let howl = musicCache.get(track);
  if (!howl) {
    try {
      howl = new Howl({
        src: [MUSIC_SOURCES[track]],
        preload: false,
        loop: true,
        html5: true, // stream longer music instead of fully decoding it
        volume: 0,
      });
      howl.on('loaderror', () => {});
      howl.on('playerror', () => {});
      musicCache.set(track, howl);
    } catch {
      return null;
    }
  }
  return howl;
}

/** Play a one-shot sound effect (no-op when SFX are off). */
export function sfx(name: SfxName): void {
  const s = useSettingsStore.getState();
  if (!s.sfx) return;
  const howl = getSfx(name);
  if (!howl) return;
  try {
    howl.volume(s.sfxVolume);
    howl.play();
  } catch {
    // Autoplay/decoding hiccup — ignore.
  }
}

let currentTrack: MusicTrack | null = null;
let unlockArmed = false;

/**
 * Browsers block audio until the page receives a user gesture. On a fresh load
 * (e.g. a refresh) music settings are already "on", so `playMusic` runs before
 * any gesture and the browser silently blocks `play()` — and nothing retries it.
 * This arms a one-time gesture listener that re-asserts the intended track the
 * moment the player next clicks/taps/keys, so music starts as soon as it's
 * allowed. No-ops if the track is already playing.
 */
function armUnlock(): void {
  if (unlockArmed || typeof window === 'undefined') return;
  unlockArmed = true;
  const resume = () => {
    window.removeEventListener('pointerdown', resume);
    window.removeEventListener('keydown', resume);
    window.removeEventListener('touchstart', resume);
    unlockArmed = false;
    if (currentTrack) startTrack(currentTrack);
  };
  window.addEventListener('pointerdown', resume);
  window.addEventListener('keydown', resume);
  window.addEventListener('touchstart', resume);
}

/** Play the current track at the settings volume; retry on a gesture if blocked. */
function startTrack(track: MusicTrack): void {
  const s = useSettingsStore.getState();
  const howl = getMusic(track);
  if (!howl || !s.music) return;
  if (howl.playing()) {
    howl.volume(s.musicVolume);
    return;
  }
  try {
    howl.play();
    howl.fade(0, s.musicVolume, FADE_MS);
  } catch {
    /* blocked — the unlock listener below recovers it */
  }
  // Autoplay blocks are reported asynchronously, so don't trust playing() right
  // now — always arm a gesture retry. It no-ops if the track is already playing.
  armUnlock();
}

/** Switch background music to `track` (or stop, when null), respecting settings. */
export function playMusic(track: MusicTrack | null): void {
  const s = useSettingsStore.getState();
  const target = s.music ? track : null;
  if (target === currentTrack) {
    // Same track — sync volume, and (re)start it if autoplay blocked it earlier.
    if (target) startTrack(target);
    return;
  }

  // Fade out + stop whatever was playing — unless it's picked again before the
  // fade ends (sailing out of a sea area and straight back): changing its
  // volume cancels the fade, which still fires 'fade', and it must play on.
  if (currentTrack) {
    const leaving = currentTrack;
    const prev = getMusic(leaving);
    if (prev) {
      try {
        prev.fade(prev.volume(), 0, FADE_MS);
        prev.once('fade', () => {
          if (currentTrack !== leaving) prev.stop();
        });
      } catch {
        try {
          prev.stop();
        } catch {
          /* ignore */
        }
      }
    }
  }

  currentTrack = target;
  if (target) startTrack(target);
}

export function stopMusic(): void {
  playMusic(null);
}

type Screen = 'topics' | 'quiz' | 'avatar' | 'world' | 'battle';

/** Music for each kind of place in the world (#75 Phase 1). */
export const ZONE_KIND_TRACK: Record<ZoneKind, MusicTrack> = {
  overworld: 'overworld',
  field: 'overworld',
  town: 'town',
  dungeon: 'cave',
  shrine: 'shrine',
};

/** Music for each sea area (#75 item 14, `seaAreaAt`) — out on the water it wins over the place's kind. */
export const SEA_TRACK: Record<SeaArea, MusicTrack> = {
  'dawnreach-waters': 'sailing',
  'silver-shallows': 'shallows',
  'great-fogbank': 'fogbank',
};

/**
 * Which track suits the current screen. In the world it follows the sea area
 * you're in, else the kind of place (towns, caves and shrines each have their
 * own theme). Pure — unit-tested.
 */
export function trackForScreen(
  screen: Screen,
  isBoss = false,
  zoneKind: ZoneKind = 'field',
  sea: SeaArea | null = null,
): MusicTrack | null {
  switch (screen) {
    case 'topics':
    case 'quiz':
    case 'avatar':
      return 'title';
    case 'world':
      return sea ? SEA_TRACK[sea] : ZONE_KIND_TRACK[zoneKind];
    case 'battle':
      return isBoss ? 'boss' : 'battle';
    default:
      return null;
  }
}

/**
 * Drive background music from the current screen. Re-runs whenever the screen,
 * boss flag, or the music on/off + volume settings change.
 *
 * While inside the Spire, music is owned by `SpireOverlay` (it alone knows the
 * floor and so chooses spire vs final-boss music) — this hook steps aside so the
 * two never fight over the same track.
 */
export function useScreenMusic(
  screen: Screen,
  isBoss = false,
  inSpire = false,
  zoneKind: ZoneKind = 'field',
  sea: SeaArea | null = null,
): void {
  const music = useSettingsStore((s) => s.music);
  const musicVolume = useSettingsStore((s) => s.musicVolume);
  useEffect(() => {
    if (inSpire) return; // SpireOverlay drives music while the climb is open
    playMusic(trackForScreen(screen, isBoss, zoneKind, sea));
  }, [screen, isBoss, inSpire, zoneKind, sea, music, musicVolume]);
}
