import { useEffect } from 'react';
import { Howl } from 'howler';
import { useSettingsStore } from '../store/settingsStore';
import type { ZoneKind } from '../content/zones';
import type { SeaArea } from '../content/boat';

/**
 * The game's audio engine (Howler.js). Two responsibilities: fire one-shot
 * **sound effects** (`sfx`) and play looping **background music** that follows
 * the current screen (`useScreenMusic`). Both honour the device settings —
 * audio is off by default, so every call here is a silent no-op until the
 * player enables Music / Sound in the menu.
 *
 * Files live in `public/audio/16bit/` (see `public/audio/README.md`). Load
 * errors are swallowed, so a missing file never breaks gameplay.
 */

export type SfxName =
  | 'correct'
  | 'wrong'
  | 'attack'
  | 'hit'
  | 'gate'
  | 'chest'
  | 'levelup'
  | 'victory'
  | 'select'
  // Battle (spells, defending, damage, Ember)
  | 'impact'
  | 'enemyAttack'
  | 'spell'
  | 'heal'
  | 'guard'
  | 'block'
  | 'shatter'
  | 'roar'
  | 'pair'
  | 'swap'
  | 'charge'
  | 'streak';

export type MusicTrack =
  | 'title'
  | 'overworld'
  | 'town'
  | 'cave'
  | 'shrine'
  | 'sailing'
  | 'shallows'
  | 'fogbank'
  | 'spire'
  | 'spireArchive'
  | 'spireThicket'
  | 'spireStars'
  | 'spireEngine'
  | 'finalBoss'
  | 'battle'
  | 'boss'
  | 'victory';

/**
 * The 16-bit chiptune set generated by `tools/assets/audio.py`
 * (`public/audio/16bit/`). Any Howler-supported file works — just change the
 * path here. Every file in `public/audio/` is one of these (audio.test).
 */
export const SFX_SOURCES: Record<SfxName, string> = {
  hit: '/audio/16bit/sfx/hit.mp3', // player takes damage in battle
  wrong: '/audio/16bit/sfx/wrong.mp3', // a question answered incorrectly
  victory: '/audio/16bit/sfx/victory.mp3', // a battle is won (fanfare jingle)
  levelup: '/audio/16bit/sfx/levelup.mp3', // the level-up / choose-a-perk modal
  correct: '/audio/16bit/sfx/correct.mp3',
  attack: '/audio/16bit/sfx/attack.mp3',
  gate: '/audio/16bit/sfx/gate.mp3',
  chest: '/audio/16bit/sfx/chest.mp3',
  select: '/audio/16bit/sfx/select.mp3',
  impact: '/audio/16bit/sfx/impact.mp3', // an enemy takes damage
  enemyAttack: '/audio/16bit/sfx/enemyAttack.mp3', // the enemy lunges
  spell: '/audio/16bit/sfx/spell.mp3', // a spell is cast (landed)
  heal: '/audio/16bit/sfx/heal.mp3', // HP restored (Mend, potion, a healer enemy)
  guard: '/audio/16bit/sfx/guard.mp3', // a guard / shield is raised
  block: '/audio/16bit/sfx/block.mp3', // an enemy hit is fully blocked
  shatter: '/audio/16bit/sfx/shatter.mp3', // a shielded enemy's shield breaks
  roar: '/audio/16bit/sfx/roar.mp3', // Ember attacks
  pair: '/audio/16bit/sfx/pair.mp3', // a hero + companion Pair Attack
  swap: '/audio/16bit/sfx/swap.mp3', // a companion swaps in
  charge: '/audio/16bit/sfx/charge.mp3', // an enemy gathers power (telegraphed blow)
  streak: '/audio/16bit/sfx/streak.mp3', // correct answers in a row
};

export const MUSIC_SOURCES: Record<MusicTrack, string> = {
  overworld: '/audio/16bit/music/overworld.mp3', // the overworld + open fields
  town: '/audio/16bit/music/town.mp3', // towns (#75 Phase 1)
  cave: '/audio/16bit/music/cave.mp3', // caves and dungeons
  shrine: '/audio/16bit/music/shrine.mp3', // shrines
  // The sea (#75 item 14): one loop per sea area (`SEA_TRACK`).
  sailing: '/audio/16bit/music/sailing.mp3', // a shanty: sailing Dawnreach's waters
  shallows: '/audio/16bit/music/shallows.mp3', // the Silver Shallows, afloat or on its islets
  fogbank: '/audio/16bit/music/fogbank.mp3', // misty: near the Great Fogbank
  spire: '/audio/16bit/music/spire.mp3', // the Spire's entrance + intro
  // One spooky loop per Spire floor (#74); the throne floor uses finalBoss.
  spireArchive: '/audio/16bit/music/spireArchive.mp3',
  spireThicket: '/audio/16bit/music/spireThicket.mp3',
  spireStars: '/audio/16bit/music/spireStars.mp3',
  spireEngine: '/audio/16bit/music/spireEngine.mp3',
  finalBoss: '/audio/16bit/music/finalBoss.mp3', // the Umbra fight (Spire boss floor)
  battle: '/audio/16bit/music/battle.mp3', // regular battles
  boss: '/audio/16bit/music/boss.mp3', // area bosses (Fiends, wardens)
  title: '/audio/16bit/music/title.mp3', // menu screens
  victory: '/audio/16bit/music/victory.mp3', // looping victory theme — unused; the win uses the sfx jingle
};

const FADE_MS = 600;
/** A left track is unloaded this long after its fade-out starts: the fade, plus a margin. */
const RETIRE_MS = FADE_MS + 150;

// Lazily-built, cached SFX Howls — one per registered source, reused across plays.
const sfxCache = new Map<SfxName, Howl>();

/**
 * A music track's Howl. It lives from the moment its track is picked until it
 * has faded out after being left: then it's unloaded, and picking the track
 * again builds a fresh one (the file comes from the browser's cache).
 */
interface Music {
  howl: Howl;
  /** play() was asked for and not refused — Howler is loading or playing it. */
  started: boolean;
  /** Its sound, once play() has been asked for. */
  id: number | null;
}
const musicCache = new Map<MusicTrack, Music>();
/** Left tracks fading out: each one's timer unloads it, unless it's picked again first. */
const retiring = new Map<MusicTrack, ReturnType<typeof setTimeout>>();

function getSfx(name: SfxName): Howl | null {
  let howl = sfxCache.get(name);
  if (!howl) {
    try {
      howl = new Howl({ src: [SFX_SOURCES[name]], preload: false, volume: 1 });
      // A missing/undecodable file must never throw into gameplay.
      howl.on('loaderror', () => {});
      howl.on('playerror', () => {});
      sfxCache.set(name, howl);
    } catch {
      return null;
    }
  }
  return howl;
}

function getMusic(track: MusicTrack): Music | null {
  let music = musicCache.get(track);
  if (!music) {
    try {
      const howl = new Howl({
        src: [MUSIC_SOURCES[track]],
        preload: false,
        loop: true,
        html5: true, // stream longer music instead of fully decoding it
        volume: 0,
      });
      const m: Music = { howl, started: false, id: null };
      howl.on('loaderror', () => {});
      // Autoplay refused it — the next gesture plays it again (`armUnlock`).
      howl.on('playerror', () => {
        m.started = false;
      });
      music = m;
      musicCache.set(track, music);
    } catch {
      return null;
    }
  }
  return music;
}

/** Play a one-shot sound effect (no-op when SFX are off). */
export function sfx(name: SfxName): void {
  const s = useSettingsStore.getState();
  if (!s.sfx) return;
  const howl = getSfx(name);
  if (!howl) return;
  try {
    howl.volume(s.sfxVolume);
    howl.play();
  } catch {
    // Autoplay/decoding hiccup — ignore.
  }
}

let currentTrack: MusicTrack | null = null;
let unlockArmed = false;

/**
 * Browsers block audio until the page receives a user gesture. On a fresh load
 * (e.g. a refresh) music settings are already "on", so `playMusic` runs before
 * any gesture and the browser silently blocks `play()` — and nothing retries it.
 * This arms a one-time gesture listener that re-asserts the intended track the
 * moment the player next clicks/taps/keys, so music starts as soon as it's
 * allowed. No-ops if the track is already playing.
 */
function armUnlock(): void {
  if (unlockArmed || typeof window === 'undefined') return;
  unlockArmed = true;
  const resume = () => {
    window.removeEventListener('pointerdown', resume);
    window.removeEventListener('keydown', resume);
    window.removeEventListener('touchstart', resume);
    unlockArmed = false;
    if (currentTrack) startTrack(currentTrack);
  };
  window.addEventListener('pointerdown', resume);
  window.addEventListener('keydown', resume);
  window.addEventListener('touchstart', resume);
}

/*
 * Howler's html5 mode is busy while a play() starts — the first one, and again
 * at every loop point, where it restarts the track with stop() + play(). A
 * fade(), volume() or stop() asked for meanwhile is queued, and after a play()
 * on a loaded track that queue never runs. So a fade-in asked for along with
 * the play left a track that came back (the overworld after a battle) at volume
 * 0, and a battle that began as the overworld looped left the overworld playing
 * on under the battle music for good — its fade-out, and so its stop, never ran
 * (#115). Hence: a track fades in once its 'play' event says it's really
 * playing; it's played once until autoplay refuses it (keys pressed while it
 * loads don't queue more plays); and a left track is unloaded once its fade-out
 * is over — unloading stops it even mid-play() — or at once if it's not audible
 * yet.
 */

/**
 * The volume a track's sound is playing at (0 when it isn't playing). Not the
 * Howl's own volume(): a loop point mid-fade-out (Howler's restart ends the fade
 * at its target) leaves the sound at 0 while the Howl still says where it began.
 */
function playingAt(music: Music): number {
  if (music.id === null || !music.howl.playing(music.id)) return 0;
  const vol = music.howl.volume(music.id);
  return typeof vol === 'number' ? vol : 0;
}

/** Play the current track at the settings volume; retry on a gesture if blocked. */
function startTrack(track: MusicTrack): void {
  const s = useSettingsStore.getState();
  if (!s.music) return;
  const music = getMusic(track);
  if (!music) return;
  const fadingOut = keep(track); // picked again before its fade-out ended — it plays on
  const { howl } = music;
  try {
    if (!music.started) {
      const id = howl.play();
      music.id = id;
      music.started = true;
      howl.once(
        'play',
        () => {
          // Left while it was starting? Then it's already been unloaded.
          if (musicCache.get(track) !== music || currentTrack !== track) return;
          const vol = useSettingsStore.getState().musicVolume;
          if (vol > 0) howl.fade(0, vol, FADE_MS);
        },
        id,
      );
    } else if (howl.playing() && (fadingOut || playingAt(music) !== s.musicVolume)) {
      // Setting it stops a fade-out. Otherwise only on a change: this runs on
      // every key press (`armUnlock`), and one landing as the track loops would
      // be queued by Howler and replayed later.
      howl.volume(s.musicVolume);
    }
  } catch {
    /* blocked — the unlock listener below recovers it */
  }
  // Autoplay blocks are reported asynchronously, so don't trust playing() right
  // now — always arm a gesture retry. It no-ops if the track is already playing.
  armUnlock();
}

/** Stop waiting to unload `track` — it's been picked again. True if it was fading out. */
function keep(track: MusicTrack): boolean {
  const timer = retiring.get(track);
  if (timer === undefined) return false;
  clearTimeout(timer);
  retiring.delete(track);
  return true;
}

/** Unload `track`'s Howl: it stops whatever Howler is in the middle of. */
function unload(track: MusicTrack): void {
  keep(track);
  const music = musicCache.get(track);
  if (!music) return;
  musicCache.delete(track);
  try {
    music.howl.unload();
  } catch {
    /* ignore */
  }
}

/**
 * Fade a left track out, then unload it — unless it's picked again before then
 * (sailing out of a sea area and straight back), when it plays on. A track not
 * audible yet (still loading, or refused by autoplay) is unloaded at once.
 */
function retire(track: MusicTrack): void {
  const music = musicCache.get(track);
  if (!music) return;
  keep(track);
  const vol = playingAt(music);
  if (!(vol > 0)) {
    unload(track);
    return;
  }
  try {
    music.howl.fade(vol, 0, FADE_MS);
  } catch {
    /* the timer still unloads it */
  }
  retiring.set(
    track,
    setTimeout(() => {
      retiring.delete(track);
      if (currentTrack !== track) unload(track);
    }, RETIRE_MS),
  );
}

/** Switch background music to `track` (or stop, when null), respecting settings. */
export function playMusic(track: MusicTrack | null): void {
  const s = useSettingsStore.getState();
  const target = s.music ? track : null;
  if (target === currentTrack) {
    // Same track — sync volume, and (re)start it if autoplay blocked it earlier.
    if (target) startTrack(target);
    return;
  }

  if (currentTrack) retire(currentTrack);
  currentTrack = target;
  if (target) startTrack(target);
}

export function stopMusic(): void {
  playMusic(null);
}

type Screen = 'topics' | 'quiz' | 'avatar' | 'world' | 'battle';

/** Music for each kind of place in the world (#75 Phase 1). */
export const ZONE_KIND_TRACK: Record<ZoneKind, MusicTrack> = {
  overworld: 'overworld',
  field: 'overworld',
  town: 'town',
  dungeon: 'cave',
  shrine: 'shrine',
};

/** Music for each sea area (#75 item 14, `seaAreaAt`) — out on the water it wins over the place's kind. */
export const SEA_TRACK: Record<SeaArea, MusicTrack> = {
  'dawnreach-waters': 'sailing',
  'silver-shallows': 'shallows',
  'great-fogbank': 'fogbank',
};

/**
 * Which track suits the current screen. In the world it follows the sea area
 * you're in, else the kind of place (towns, caves and shrines each have their
 * own theme). Pure — unit-tested.
 */
export function trackForScreen(
  screen: Screen,
  isBoss = false,
  zoneKind: ZoneKind = 'field',
  sea: SeaArea | null = null,
): MusicTrack | null {
  switch (screen) {
    case 'topics':
    case 'quiz':
    case 'avatar':
      return 'title';
    case 'world':
      return sea ? SEA_TRACK[sea] : ZONE_KIND_TRACK[zoneKind];
    case 'battle':
      return isBoss ? 'boss' : 'battle';
    default:
      return null;
  }
}

/**
 * Drive background music from the current screen. Re-runs whenever the screen,
 * boss flag, or the music on/off + volume settings change.
 *
 * While inside the Spire, music is owned by `SpireOverlay` (it alone knows the
 * floor and so chooses spire vs final-boss music) — this hook steps aside so the
 * two never fight over the same track.
 */
export function useScreenMusic(
  screen: Screen,
  isBoss = false,
  inSpire = false,
  zoneKind: ZoneKind = 'field',
  sea: SeaArea | null = null,
): void {
  const music = useSettingsStore((s) => s.music);
  const musicVolume = useSettingsStore((s) => s.musicVolume);
  useEffect(() => {
    if (inSpire) return; // SpireOverlay drives music while the climb is open
    playMusic(trackForScreen(screen, isBoss, zoneKind, sea));
  }, [screen, isBoss, inSpire, zoneKind, sea, music, musicVolume]);
}
