-- Hazel Quest — apply AND record every migration (0001 → 0011).
-- GENERATED by scripts/build-apply-all.mjs from supabase/migrations/ — do not
-- edit by hand; add a new migration and run `npm run db:bundle`.
--
-- Paste the whole file into the Supabase SQL Editor and click Run.
--   * Safe to run on a fresh project, a partly migrated one, or a finished one:
--     every statement is idempotent (IF NOT EXISTS / OR REPLACE /
--     DROP POLICY IF EXISTS + CREATE), so re-running never fails and it also
--     repairs a missing or wrong policy/grant/column.
--   * All-or-nothing: it runs in one transaction; any error rolls it all back.
--   * Each migration is recorded in supabase_migrations.schema_migrations, so
--     `supabase db push` afterwards sees them as applied.
--   * Afterwards, the SELECT at the bottom lists what is recorded.

begin;

-- The history table the Supabase CLI uses (created here if this project has
-- never run `supabase db push`).
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version    text primary key,
  statements text[],
  name       text
);

-- ============================================================================
-- 0001_create_profiles.sql
-- ============================================================================
-- Hazel Quest — profiles table
-- Run in the Supabase SQL Editor (or `supabase db push`).
--
-- Stores each player's birth year/month (for age-based difficulty) and a
-- per-topic skill level. One row per auth user, created automatically on
-- sign-up from the metadata passed to supabase.auth.signUp().

create table if not exists public.profiles (
  id            uuid        primary key references auth.users (id) on delete cascade,
  birth_year    smallint    not null,
  birth_month   smallint    not null check (birth_month between 1 and 12),
  -- { "math": 3, "science": 1, ... } — per-topic skill level (integers).
  skill_levels  jsonb       not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Row Level Security: a user may only see and change their own profile.
alter table public.profiles enable row level security;

drop policy if exists "Profiles are viewable by their owner" on public.profiles;
create policy "Profiles are viewable by their owner"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Auto-create a profile row when a new auth user signs up. Reads birth_year /
-- birth_month from the sign-up metadata (raw_user_meta_data).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, birth_year, birth_month)
  values (
    new.id,
    (new.raw_user_meta_data ->> 'birth_year')::smallint,
    (new.raw_user_meta_data ->> 'birth_month')::smallint
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0001', 'create_profiles', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0002_add_xp.sql
-- ============================================================================
-- Hazel Quest — add player XP
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0001.
--
-- XP accumulates from correct answers and NPC defeats. The player's level is
-- derived from XP in the client (see src/lib/level.ts) — it is not stored.

alter table public.profiles
  add column if not exists xp integer not null default 0;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0002', 'add_xp', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0003_questions_cache.sql
-- ============================================================================
-- Hazel Quest — question cache
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0002.
--
-- Generated questions are stored here so they can be randomly reused instead
-- of always calling the Claude API. `times_asked` counts how often each
-- question has been served. Only the generate-questions edge function (service
-- role) touches this table — RLS is on with no policies, denying direct
-- client access.

create table if not exists public.questions (
  id            uuid        primary key default gen_random_uuid(),
  topic         text        not null,
  level         smallint    not null,
  text          text        not null,
  options       jsonb       not null,
  correct_index smallint    not null,
  explanation   text,
  times_asked   integer     not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists questions_topic_level_idx
  on public.questions (topic, level);

alter table public.questions enable row level security;

-- Atomically bump the ask-counter for a set of questions.
create or replace function public.increment_question_usage(ids uuid[])
returns void
language sql
as $$
  update public.questions
  set times_asked = times_asked + 1
  where id = any(ids);
$$;

-- Only the edge function (service role) should call this.
revoke execute on function public.increment_question_usage(uuid[]) from anon, authenticated;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0003', 'questions_cache', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0004_power_ups.sql
-- ============================================================================
-- Hazel Quest — player power-ups
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0003.
--
-- On each level-up the player chooses a power-up; this column holds how many
-- of each they have ({ "attack": 2, "vitality": 1, ... }).

alter table public.profiles
  add column if not exists power_ups jsonb not null default '{}'::jsonb;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0004', 'power_ups', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0005_questions_grants.sql
-- ============================================================================
-- Hazel Quest — explicit grants for the question cache
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0003.
--
-- Migration 0003 created the `questions` table and enabled RLS, relying on
-- the public-schema default privileges to give `service_role` table access.
-- On projects where those defaults have been tightened, the edge function
-- logs `cache insert failed: permission denied for table questions` — RLS
-- is bypassed for the service role, but it still needs the underlying GRANTs.
-- This migration makes the grants explicit so the cache works on any project.

grant usage on schema public to service_role;

grant select, insert, update on public.questions to service_role;

grant execute on function public.increment_question_usage(uuid[]) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0005', 'questions_grants', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0006_question_views_and_flags.sql
-- ============================================================================
-- Hazel Quest — per-player view history + flag-a-question
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0005.
--
-- question_views: every question a profile is served. The edge function reads
-- the most recent 100 per profile to exclude from the cache pool (#24 dedupe).
-- question_flags: a kid (or parent) can flag a question — any single flag
-- quarantines that question from the cache pool until manual review (#26).

create table if not exists public.question_views (
  id          uuid        primary key default gen_random_uuid(),
  profile_id  uuid        not null references public.profiles(id) on delete cascade,
  question_id uuid        not null references public.questions(id) on delete cascade,
  seen_at     timestamptz not null default now()
);

-- Lookup pattern: most recent N views for a single profile.
create index if not exists question_views_profile_seen_idx
  on public.question_views (profile_id, seen_at desc);

alter table public.question_views enable row level security;

-- Only the edge function (service role) reads / writes views. No client policy.
grant select, insert on public.question_views to service_role;

create table if not exists public.question_flags (
  id          uuid        primary key default gen_random_uuid(),
  question_id uuid        not null references public.questions(id) on delete cascade,
  profile_id  uuid        not null references public.profiles(id) on delete cascade,
  reason      text,
  created_at  timestamptz not null default now()
);

-- Lookup pattern: "is this question flagged?" — by question_id.
create index if not exists question_flags_question_idx
  on public.question_flags (question_id);

alter table public.question_flags enable row level security;

-- Authenticated users may insert flags only for themselves. They cannot read
-- flags from the client; the edge function uses the service role to quarantine.
drop policy if exists "users insert their own flags" on public.question_flags;
create policy "users insert their own flags"
  on public.question_flags
  for insert
  to authenticated
  with check (profile_id = auth.uid());

grant insert on public.question_flags to authenticated;
grant select, insert on public.question_flags to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0006', 'question_views_and_flags', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0007_add_streak.sql
-- ============================================================================
-- Hazel Quest — daily streak hook (#28)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0006.
--
-- Adds three columns to `profiles`:
--   current_streak   — consecutive days played, advances by 1 each new day.
--   longest_streak   — high-water mark across all time, for parent dashboard.
--   last_played_on   — local-date (YYYY-MM-DD) of the player's last round.
--
-- The streak math runs client-side (lib/streak.ts) using the player's local
-- calendar day — no server-side cron / trigger needed.

alter table public.profiles
  add column if not exists current_streak integer     not null default 0,
  add column if not exists longest_streak integer     not null default 0,
  add column if not exists last_played_on date;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0007', 'add_streak', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0008_saves.sql
-- ============================================================================
-- #37: per-player JRPG save files (also resolves #12 — progress tied to the
-- user, not the browser). One row per profile, whole save as JSONB.

create table if not exists public.saves (
  profile_id uuid primary key references public.profiles (id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.saves enable row level security;

drop policy if exists "Players read their own save" on public.saves;
create policy "Players read their own save"
  on public.saves for select
  using (auth.uid() = profile_id);

drop policy if exists "Players create their own save" on public.saves;
create policy "Players create their own save"
  on public.saves for insert
  with check (auth.uid() = profile_id);

drop policy if exists "Players update their own save" on public.saves;
create policy "Players update their own save"
  on public.saves for update
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);

-- Mirror 0005's explicit grants — this project's public-schema default
-- privileges are tightened, so RLS alone isn't enough.
grant select, insert, update on public.saves to authenticated;
grant select, insert, update on public.saves to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0008', 'saves', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0009_question_quota.sql
-- ============================================================================
-- Hazel Quest — per-player request log + quota for generate-questions (#88)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0008.
--
-- The edge function calls the Claude API on the project's key, so an
-- unthrottled caller could run up the bill. Every call is logged here and
-- checked by `begin_question_request`:
--   * a per-player request rate (calls per minute) → over it: 429
--   * a per-player daily budget of FRESH (Claude-generated) questions
--   * a project-wide daily budget of fresh questions (the real cost ceiling)
-- When a fresh budget is spent the function still serves cached questions,
-- so kids keep playing from the shared bank. The `questions` bank itself is
-- never pruned (product decision, ISSUES #68).

create table if not exists public.question_requests (
  id           bigint      generated always as identity primary key,
  profile_id   uuid        not null references auth.users (id) on delete cascade,
  requested_at timestamptz not null default now(),
  -- Filled in after generation: how many questions actually came from Claude.
  fresh_count  integer     not null default 0
);

-- Lookup patterns: one player's recent calls; everyone's calls in the last day.
create index if not exists question_requests_profile_time_idx
  on public.question_requests (profile_id, requested_at desc);
create index if not exists question_requests_time_idx
  on public.question_requests (requested_at);

alter table public.question_requests enable row level security;
-- No client policies: only the edge function (service role) touches this.
grant select, insert, update on public.question_requests to service_role;

-- Atomically check the caller's quota and log the call. Serialized per player
-- with an advisory lock, so a burst of parallel calls can't all slip under
-- the limit. Returns:
--   allowed         false → over the per-minute rate (caller returns 429)
--   fresh_allowance how many fresh questions this call may generate (≥ 0)
--   request_id      the log row; the caller records fresh_count on it
create or replace function public.begin_question_request(
  p_profile         uuid,
  p_max_per_minute  integer,
  p_fresh_per_day   integer,
  p_fresh_global    integer
)
returns table (allowed boolean, fresh_allowance integer, request_id bigint)
language plpgsql
set search_path = public
as $$
declare
  v_recent       integer;
  v_fresh_mine   integer;
  v_fresh_all    integer;
  v_id           bigint;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_profile::text, 0));

  select count(*) into v_recent
    from question_requests
   where profile_id = p_profile
     and requested_at > now() - interval '1 minute';

  if v_recent >= p_max_per_minute then
    return query select false, 0, null::bigint;
    return;
  end if;

  select coalesce(sum(fresh_count), 0) into v_fresh_mine
    from question_requests
   where profile_id = p_profile
     and requested_at > now() - interval '1 day';

  select coalesce(sum(fresh_count), 0) into v_fresh_all
    from question_requests
   where requested_at > now() - interval '1 day';

  insert into question_requests (profile_id) values (p_profile)
  returning id into v_id;

  return query select
    true,
    greatest(0, least(p_fresh_per_day - v_fresh_mine, p_fresh_global - v_fresh_all))::integer,
    v_id;
end;
$$;

-- Supabase grants EXECUTE on new public functions to anon + authenticated by
-- default; revoke so a client can never burn another player's quota.
revoke all on function public.begin_question_request(uuid, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.begin_question_request(uuid, integer, integer, integer) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0009', 'question_quota', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0010_access_hardening.sql
-- ============================================================================
-- Hazel Quest — access hardening from the migrations review (#90)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0009.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- Fixes are a NEW migration instead of edits to 0001/0003: projects that
-- already recorded 0001/0003 (e.g. via `supabase db push`) would never re-run
-- an edited old file, so the fix has to arrive as the next version.

-- 1) profiles had no explicit table grants. The client reads/inserts/updates
--    its own row (profileStore), protected by 0001's RLS policies; on a
--    project with tightened public-schema defaults (see 0005/0008) every
--    profile write failed with "permission denied" and XP never saved.
--    Mirrors 0008's grants for `saves`. RLS still limits rows to the owner.
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.profiles to service_role;

-- 2) The sign-up trigger required birth-date metadata: creating a user from
--    the dashboard, an invite, or a future OAuth / parent-account flow failed
--    the whole sign-up ("Database error saving new user"). Now it only seeds
--    the profile when both values are present and valid; otherwise the app
--    creates the row on first load (profileStore.loadProfile) with a default
--    age. `on conflict do nothing` keeps it safe if a row already exists.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_year  text := new.raw_user_meta_data ->> 'birth_year';
  v_month text := new.raw_user_meta_data ->> 'birth_month';
begin
  if v_year ~ '^\d{4}$' and v_month ~ '^\d{1,2}$' and v_month::int between 1 and 12 then
    insert into public.profiles (id, birth_year, birth_month)
    values (new.id, v_year::smallint, v_month::smallint)
    on conflict (id) do nothing;
  end if;
  return new;
end;
$$;

-- 3) increment_question_usage stayed callable by everyone through Postgres's
--    default PUBLIC execute grant (0003 only revoked anon/authenticated).
--    Harmless today (invoker rights + RLS → 0 rows), but only the edge
--    function should call it. 0005 already grants it to service_role.
revoke execute on function public.increment_question_usage(uuid[]) from public, anon, authenticated;
grant execute on function public.increment_question_usage(uuid[]) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0010', 'access_hardening', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0011_save_version_guard.sql
-- ============================================================================
-- Hazel Quest — an older game can never overwrite a newer save (#101h)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0010.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- Each save records the version of its shape (`data->>'version'`;
-- `SAVE_VERSION` in src/lib/save.ts — 2 since #75 item 8). A client already
-- refuses to LOAD a save from a newer version than itself, but a tab that was
-- open when a newer version shipped still has its older save in memory, and
-- its next upload would replace the newer save. This trigger refuses any
-- update that would lower a save's version; the client then shows "refresh to
-- update" (saveStore: the error code `save_version_conflict`).
--
-- A save without a numeric version (or with junk there) counts as version 1,
-- as the client reads it (`saveVersionOf`).

create or replace function public.saves_keep_newest_version()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_old integer := case when jsonb_typeof(old.data -> 'version') = 'number'
                         and (old.data ->> 'version') ~ '^\d{1,9}$'
                        then (old.data ->> 'version')::integer else 1 end;
  v_new integer := case when jsonb_typeof(new.data -> 'version') = 'number'
                         and (new.data ->> 'version') ~ '^\d{1,9}$'
                        then (new.data ->> 'version')::integer else 1 end;
begin
  if v_new < v_old then
    raise exception 'save_version_conflict: this save was written by a newer version of the game (v%), refusing v%',
      v_old, v_new
      using hint = 'Refresh the page to update the game.';
  end if;
  return new;
end;
$$;

drop trigger if exists saves_keep_newest_version on public.saves;
create trigger saves_keep_newest_version
  before update on public.saves
  for each row execute function public.saves_keep_newest_version();

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0011', 'save_version_guard', array[]::text[])
on conflict (version) do nothing;

commit;

-- What's recorded now:
select version, name from supabase_migrations.schema_migrations order by version;
