-- Hazel Quest — apply AND record every migration (0001 → 0013).
-- GENERATED by scripts/build-apply-all.mjs from supabase/migrations/ — do not
-- edit by hand; add a new migration and run `npm run db:bundle`.
--
-- Paste the whole file into the Supabase SQL Editor and click Run.
--   * Safe to run on a fresh project, a partly migrated one, or a finished one:
--     every statement is idempotent (IF NOT EXISTS / OR REPLACE /
--     DROP POLICY IF EXISTS + CREATE), so re-running never fails and it also
--     repairs a missing or wrong policy/grant/column.
--   * All-or-nothing: it runs in one transaction; any error rolls it all back.
--   * Each migration is recorded in supabase_migrations.schema_migrations, so
--     `supabase db push` afterwards sees them as applied.
--   * Afterwards, the SELECT at the bottom lists what is recorded.

begin;

-- The history table the Supabase CLI uses (created here if this project has
-- never run `supabase db push`).
create schema if not exists supabase_migrations;
create table if not exists supabase_migrations.schema_migrations (
  version    text primary key,
  statements text[],
  name       text
);

-- ============================================================================
-- 0001_create_profiles.sql
-- ============================================================================
-- Hazel Quest — profiles table
-- Run in the Supabase SQL Editor (or `supabase db push`).
--
-- Stores each player's birth year/month (for age-based difficulty) and a
-- per-topic skill level. One row per auth user, created automatically on
-- sign-up from the metadata passed to supabase.auth.signUp().

create table if not exists public.profiles (
  id            uuid        primary key references auth.users (id) on delete cascade,
  birth_year    smallint    not null,
  birth_month   smallint    not null check (birth_month between 1 and 12),
  -- { "math": 3, "science": 1, ... } — per-topic skill level (integers).
  skill_levels  jsonb       not null default '{}'::jsonb,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

-- Row Level Security: a user may only see and change their own profile.
alter table public.profiles enable row level security;

drop policy if exists "Profiles are viewable by their owner" on public.profiles;
create policy "Profiles are viewable by their owner"
  on public.profiles for select
  using (auth.uid() = id);

drop policy if exists "Users can insert their own profile" on public.profiles;
create policy "Users can insert their own profile"
  on public.profiles for insert
  with check (auth.uid() = id);

drop policy if exists "Users can update their own profile" on public.profiles;
create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id)
  with check (auth.uid() = id);

-- Auto-create a profile row when a new auth user signs up. Reads birth_year /
-- birth_month from the sign-up metadata (raw_user_meta_data).
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, birth_year, birth_month)
  values (
    new.id,
    (new.raw_user_meta_data ->> 'birth_year')::smallint,
    (new.raw_user_meta_data ->> 'birth_month')::smallint
  );
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0001', 'create_profiles', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0002_add_xp.sql
-- ============================================================================
-- Hazel Quest — add player XP
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0001.
--
-- XP accumulates from correct answers and NPC defeats. The player's level is
-- derived from XP in the client (see src/lib/level.ts) — it is not stored.

alter table public.profiles
  add column if not exists xp integer not null default 0;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0002', 'add_xp', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0003_questions_cache.sql
-- ============================================================================
-- Hazel Quest — question cache
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0002.
--
-- Generated questions are stored here so they can be randomly reused instead
-- of always calling the Claude API. `times_asked` counts how often each
-- question has been served. Only the generate-questions edge function (service
-- role) touches this table — RLS is on with no policies, denying direct
-- client access.

create table if not exists public.questions (
  id            uuid        primary key default gen_random_uuid(),
  topic         text        not null,
  level         smallint    not null,
  text          text        not null,
  options       jsonb       not null,
  correct_index smallint    not null,
  explanation   text,
  times_asked   integer     not null default 0,
  created_at    timestamptz not null default now()
);

create index if not exists questions_topic_level_idx
  on public.questions (topic, level);

alter table public.questions enable row level security;

-- Atomically bump the ask-counter for a set of questions.
create or replace function public.increment_question_usage(ids uuid[])
returns void
language sql
as $$
  update public.questions
  set times_asked = times_asked + 1
  where id = any(ids);
$$;

-- Only the edge function (service role) should call this.
revoke execute on function public.increment_question_usage(uuid[]) from anon, authenticated;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0003', 'questions_cache', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0004_power_ups.sql
-- ============================================================================
-- Hazel Quest — player power-ups
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0003.
--
-- On each level-up the player chooses a power-up; this column holds how many
-- of each they have ({ "attack": 2, "vitality": 1, ... }).

alter table public.profiles
  add column if not exists power_ups jsonb not null default '{}'::jsonb;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0004', 'power_ups', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0005_questions_grants.sql
-- ============================================================================
-- Hazel Quest — explicit grants for the question cache
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0003.
--
-- Migration 0003 created the `questions` table and enabled RLS, relying on
-- the public-schema default privileges to give `service_role` table access.
-- On projects where those defaults have been tightened, the edge function
-- logs `cache insert failed: permission denied for table questions` — RLS
-- is bypassed for the service role, but it still needs the underlying GRANTs.
-- This migration makes the grants explicit so the cache works on any project.

grant usage on schema public to service_role;

grant select, insert, update on public.questions to service_role;

grant execute on function public.increment_question_usage(uuid[]) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0005', 'questions_grants', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0006_question_views_and_flags.sql
-- ============================================================================
-- Hazel Quest — per-player view history + flag-a-question
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0005.
--
-- question_views: every question a profile is served. The edge function reads
-- the most recent 100 per profile to exclude from the cache pool (#24 dedupe).
-- question_flags: a kid (or parent) can flag a question — any single flag
-- quarantines that question from the cache pool until manual review (#26).

create table if not exists public.question_views (
  id          uuid        primary key default gen_random_uuid(),
  profile_id  uuid        not null references public.profiles(id) on delete cascade,
  question_id uuid        not null references public.questions(id) on delete cascade,
  seen_at     timestamptz not null default now()
);

-- Lookup pattern: most recent N views for a single profile.
create index if not exists question_views_profile_seen_idx
  on public.question_views (profile_id, seen_at desc);

alter table public.question_views enable row level security;

-- Only the edge function (service role) reads / writes views. No client policy.
grant select, insert on public.question_views to service_role;

create table if not exists public.question_flags (
  id          uuid        primary key default gen_random_uuid(),
  question_id uuid        not null references public.questions(id) on delete cascade,
  profile_id  uuid        not null references public.profiles(id) on delete cascade,
  reason      text,
  created_at  timestamptz not null default now()
);

-- Lookup pattern: "is this question flagged?" — by question_id.
create index if not exists question_flags_question_idx
  on public.question_flags (question_id);

alter table public.question_flags enable row level security;

-- Authenticated users may insert flags only for themselves. They cannot read
-- flags from the client; the edge function uses the service role to quarantine.
drop policy if exists "users insert their own flags" on public.question_flags;
create policy "users insert their own flags"
  on public.question_flags
  for insert
  to authenticated
  with check (profile_id = auth.uid());

grant insert on public.question_flags to authenticated;
grant select, insert on public.question_flags to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0006', 'question_views_and_flags', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0007_add_streak.sql
-- ============================================================================
-- Hazel Quest — daily streak hook (#28)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0006.
--
-- Adds three columns to `profiles`:
--   current_streak   — consecutive days played, advances by 1 each new day.
--   longest_streak   — high-water mark across all time, for parent dashboard.
--   last_played_on   — local-date (YYYY-MM-DD) of the player's last round.
--
-- The streak math runs client-side (lib/streak.ts) using the player's local
-- calendar day — no server-side cron / trigger needed.

alter table public.profiles
  add column if not exists current_streak integer     not null default 0,
  add column if not exists longest_streak integer     not null default 0,
  add column if not exists last_played_on date;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0007', 'add_streak', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0008_saves.sql
-- ============================================================================
-- #37: per-player JRPG save files (also resolves #12 — progress tied to the
-- user, not the browser). One row per profile, whole save as JSONB.

create table if not exists public.saves (
  profile_id uuid primary key references public.profiles (id) on delete cascade,
  data jsonb not null,
  updated_at timestamptz not null default now()
);

alter table public.saves enable row level security;

drop policy if exists "Players read their own save" on public.saves;
create policy "Players read their own save"
  on public.saves for select
  using (auth.uid() = profile_id);

drop policy if exists "Players create their own save" on public.saves;
create policy "Players create their own save"
  on public.saves for insert
  with check (auth.uid() = profile_id);

drop policy if exists "Players update their own save" on public.saves;
create policy "Players update their own save"
  on public.saves for update
  using (auth.uid() = profile_id)
  with check (auth.uid() = profile_id);

-- Mirror 0005's explicit grants — this project's public-schema default
-- privileges are tightened, so RLS alone isn't enough.
grant select, insert, update on public.saves to authenticated;
grant select, insert, update on public.saves to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0008', 'saves', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0009_question_quota.sql
-- ============================================================================
-- Hazel Quest — per-player request log + quota for generate-questions (#88)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0008.
--
-- The edge function calls the Claude API on the project's key, so an
-- unthrottled caller could run up the bill. Every call is logged here and
-- checked by `begin_question_request`:
--   * a per-player request rate (calls per minute) → over it: 429
--   * a per-player daily budget of FRESH (Claude-generated) questions
--   * a project-wide daily budget of fresh questions (the real cost ceiling)
-- When a fresh budget is spent the function still serves cached questions,
-- so kids keep playing from the shared bank. The `questions` bank itself is
-- never pruned (product decision, ISSUES #68).

create table if not exists public.question_requests (
  id           bigint      generated always as identity primary key,
  profile_id   uuid        not null references auth.users (id) on delete cascade,
  requested_at timestamptz not null default now(),
  -- Filled in after generation: how many questions actually came from Claude.
  fresh_count  integer     not null default 0
);

-- Lookup patterns: one player's recent calls; everyone's calls in the last day.
create index if not exists question_requests_profile_time_idx
  on public.question_requests (profile_id, requested_at desc);
create index if not exists question_requests_time_idx
  on public.question_requests (requested_at);

alter table public.question_requests enable row level security;
-- No client policies: only the edge function (service role) touches this.
grant select, insert, update on public.question_requests to service_role;

-- Atomically check the caller's quota and log the call. Serialized per player
-- with an advisory lock, so a burst of parallel calls can't all slip under
-- the limit. Returns:
--   allowed         false → over the per-minute rate (caller returns 429)
--   fresh_allowance how many fresh questions this call may generate (≥ 0)
--   request_id      the log row; the caller records fresh_count on it
create or replace function public.begin_question_request(
  p_profile         uuid,
  p_max_per_minute  integer,
  p_fresh_per_day   integer,
  p_fresh_global    integer
)
returns table (allowed boolean, fresh_allowance integer, request_id bigint)
language plpgsql
set search_path = public
as $$
declare
  v_recent       integer;
  v_fresh_mine   integer;
  v_fresh_all    integer;
  v_id           bigint;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_profile::text, 0));

  select count(*) into v_recent
    from question_requests
   where profile_id = p_profile
     and requested_at > now() - interval '1 minute';

  if v_recent >= p_max_per_minute then
    return query select false, 0, null::bigint;
    return;
  end if;

  select coalesce(sum(fresh_count), 0) into v_fresh_mine
    from question_requests
   where profile_id = p_profile
     and requested_at > now() - interval '1 day';

  select coalesce(sum(fresh_count), 0) into v_fresh_all
    from question_requests
   where requested_at > now() - interval '1 day';

  insert into question_requests (profile_id) values (p_profile)
  returning id into v_id;

  return query select
    true,
    greatest(0, least(p_fresh_per_day - v_fresh_mine, p_fresh_global - v_fresh_all))::integer,
    v_id;
end;
$$;

-- Supabase grants EXECUTE on new public functions to anon + authenticated by
-- default; revoke so a client can never burn another player's quota.
revoke all on function public.begin_question_request(uuid, integer, integer, integer)
  from public, anon, authenticated;
grant execute on function public.begin_question_request(uuid, integer, integer, integer) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0009', 'question_quota', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0010_access_hardening.sql
-- ============================================================================
-- Hazel Quest — access hardening from the migrations review (#90)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0009.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- Fixes are a NEW migration instead of edits to 0001/0003: projects that
-- already recorded 0001/0003 (e.g. via `supabase db push`) would never re-run
-- an edited old file, so the fix has to arrive as the next version.

-- 1) profiles had no explicit table grants. The client reads/inserts/updates
--    its own row (profileStore), protected by 0001's RLS policies; on a
--    project with tightened public-schema defaults (see 0005/0008) every
--    profile write failed with "permission denied" and XP never saved.
--    Mirrors 0008's grants for `saves`. RLS still limits rows to the owner.
grant select, insert, update on public.profiles to authenticated;
grant select, insert, update on public.profiles to service_role;

-- 2) The sign-up trigger required birth-date metadata: creating a user from
--    the dashboard, an invite, or a future OAuth / parent-account flow failed
--    the whole sign-up ("Database error saving new user"). Now it only seeds
--    the profile when both values are present and valid; otherwise the app
--    creates the row on first load (profileStore.loadProfile) with a default
--    age. `on conflict do nothing` keeps it safe if a row already exists.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_year  text := new.raw_user_meta_data ->> 'birth_year';
  v_month text := new.raw_user_meta_data ->> 'birth_month';
begin
  if v_year ~ '^\d{4}$' and v_month ~ '^\d{1,2}$' and v_month::int between 1 and 12 then
    insert into public.profiles (id, birth_year, birth_month)
    values (new.id, v_year::smallint, v_month::smallint)
    on conflict (id) do nothing;
  end if;
  return new;
end;
$$;

-- 3) increment_question_usage stayed callable by everyone through Postgres's
--    default PUBLIC execute grant (0003 only revoked anon/authenticated).
--    Harmless today (invoker rights + RLS → 0 rows), but only the edge
--    function should call it. 0005 already grants it to service_role.
revoke execute on function public.increment_question_usage(uuid[]) from public, anon, authenticated;
grant execute on function public.increment_question_usage(uuid[]) to service_role;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0010', 'access_hardening', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0011_save_version_guard.sql
-- ============================================================================
-- Hazel Quest — an older game can never overwrite a newer save (#101h)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0010.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- Each save records the version of its shape (`data->>'version'`;
-- `SAVE_VERSION` in src/lib/save.ts — 2 since #75 item 8). A client already
-- refuses to LOAD a save from a newer version than itself, but a tab that was
-- open when a newer version shipped still has its older save in memory, and
-- its next upload would replace the newer save. This trigger refuses any
-- update that would lower a save's version; the client then shows "refresh to
-- update" (saveStore: the error code `save_version_conflict`).
--
-- A save without a numeric version (or with junk there) counts as version 1,
-- as the client reads it (`saveVersionOf`).

create or replace function public.saves_keep_newest_version()
returns trigger
language plpgsql
set search_path = ''
as $$
declare
  v_old integer := case when jsonb_typeof(old.data -> 'version') = 'number'
                         and (old.data ->> 'version') ~ '^\d{1,9}$'
                        then (old.data ->> 'version')::integer else 1 end;
  v_new integer := case when jsonb_typeof(new.data -> 'version') = 'number'
                         and (new.data ->> 'version') ~ '^\d{1,9}$'
                        then (new.data ->> 'version')::integer else 1 end;
begin
  if v_new < v_old then
    raise exception 'save_version_conflict: this save was written by a newer version of the game (v%), refusing v%',
      v_old, v_new
      using hint = 'Refresh the page to update the game.';
  end if;
  return new;
end;
$$;

drop trigger if exists saves_keep_newest_version on public.saves;
create trigger saves_keep_newest_version
  before update on public.saves
  for each row execute function public.saves_keep_newest_version();

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0011', 'save_version_guard', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0012_parent_accounts.sql
-- ============================================================================
-- Hazel Quest — parent accounts (#118, ISSUES #89)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0011.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- A login now belongs to a grown-up, who adds their kids. Each kid is a row in
-- `profiles` with its own id and `parent_id` = the grown-up's login; a kid's
-- save and flags are reachable only through that grown-up. Kids never get an
-- email or a login of their own.
--
-- Accounts from before this become a grown-up with one kid: the profile keeps
-- its id (= the login's id), so its save, its seen questions and the app's
-- local caches all still match. Their `parents` row has no consent yet, so the
-- app asks a grown-up for it at the next sign-in.
--
-- Backward compatible: the app from before this keeps working (its profile is
-- still found by the login's id, and its sign-up still makes that first kid).

-- 1) Grown-ups and their consent.
create table if not exists public.parents (
  id              uuid        primary key references auth.users (id) on delete cascade,
  -- When, and to which wording, the grown-up agreed (null = not yet: the app asks).
  consent_at      timestamptz,
  consent_version text,
  created_at      timestamptz not null default now()
);

alter table public.parents enable row level security;

drop policy if exists "Grown-ups read their own row" on public.parents;
create policy "Grown-ups read their own row"
  on public.parents for select
  using (auth.uid() = id);

grant select on public.parents to authenticated;
grant select, insert, update on public.parents to service_role;

-- The app writes this table only through here: consent is stamped with the
-- server's clock (the client can't backdate it), and a login from before this
-- with no kid — so no row from step 2 — gets its row on agreeing.
create or replace function public.record_consent(p_version text)
returns void
language sql
security definer
set search_path = ''
as $$
  insert into public.parents (id, consent_at, consent_version)
  values (auth.uid(), now(), left(p_version, 40))
  on conflict (id) do update
    set consent_at = now(), consent_version = left(p_version, 40);
$$;
revoke execute on function public.record_consent(text) from public, anon;
grant execute on function public.record_consent(text) to authenticated;

-- 2) Kids: a profile gets a grown-up, a nickname, a tile picture and a secret
--    picture (what a kid taps to open their own profile on a shared device —
--    a lock against a sibling's slip, not a password: the grown-up's session
--    can read it).
alter table public.profiles
  add column if not exists parent_id        uuid references auth.users (id) on delete cascade,
  add column if not exists display_name     text,
  add column if not exists icon             text,
  add column if not exists picture_password text;

-- Profiles from before this are their own login's first kid.
update public.profiles set parent_id = id where parent_id is null;
alter table public.profiles alter column parent_id set not null;
-- A kid added by the app belongs to whoever is signed in (an app from before
-- this, creating a missing profile, gets the same).
alter table public.profiles alter column parent_id set default auth.uid();
create index if not exists profiles_parent_idx on public.profiles (parent_id);

-- A kid isn't a login: new kids get their own id. (An existing kid keeps
-- theirs; deleting the login still removes them, through parent_id.)
alter table public.profiles drop constraint if exists profiles_id_fkey;
alter table public.profiles alter column id set default gen_random_uuid();

alter table public.profiles drop constraint if exists profiles_display_name_length;
alter table public.profiles add constraint profiles_display_name_length
  check (display_name is null or char_length(btrim(display_name)) between 1 and 20);

-- Every grown-up who already has a kid gets their row (no consent yet).
insert into public.parents (id)
  select distinct parent_id from public.profiles
  on conflict (id) do nothing;

-- 3) Kids belong to their grown-up: read, add, change and remove them.
drop policy if exists "Profiles are viewable by their owner" on public.profiles;
drop policy if exists "Users can insert their own profile" on public.profiles;
drop policy if exists "Users can update their own profile" on public.profiles;

drop policy if exists "Grown-ups see their kids" on public.profiles;
create policy "Grown-ups see their kids"
  on public.profiles for select
  using (auth.uid() = parent_id);

drop policy if exists "Grown-ups add kids" on public.profiles;
create policy "Grown-ups add kids"
  on public.profiles for insert
  with check (auth.uid() = parent_id);

drop policy if exists "Grown-ups update their kids" on public.profiles;
create policy "Grown-ups update their kids"
  on public.profiles for update
  using (auth.uid() = parent_id)
  with check (auth.uid() = parent_id);

-- Removing a kid removes their save, seen questions and flags with them
-- (each references profiles on delete cascade).
drop policy if exists "Grown-ups remove kids" on public.profiles;
create policy "Grown-ups remove kids"
  on public.profiles for delete
  using (auth.uid() = parent_id);

grant delete on public.profiles to authenticated;

-- A kid's save: their grown-up's to read and write.
drop policy if exists "Players read their own save" on public.saves;
drop policy if exists "Players create their own save" on public.saves;
drop policy if exists "Players update their own save" on public.saves;

drop policy if exists "Grown-ups read their kids' saves" on public.saves;
create policy "Grown-ups read their kids' saves"
  on public.saves for select
  using (exists (select 1 from public.profiles p where p.id = profile_id and p.parent_id = auth.uid()));

drop policy if exists "Grown-ups create their kids' saves" on public.saves;
create policy "Grown-ups create their kids' saves"
  on public.saves for insert
  with check (exists (select 1 from public.profiles p where p.id = profile_id and p.parent_id = auth.uid()));

drop policy if exists "Grown-ups update their kids' saves" on public.saves;
create policy "Grown-ups update their kids' saves"
  on public.saves for update
  using (exists (select 1 from public.profiles p where p.id = profile_id and p.parent_id = auth.uid()))
  with check (exists (select 1 from public.profiles p where p.id = profile_id and p.parent_id = auth.uid()));

-- A flag is sent as one of the grown-up's kids.
drop policy if exists "users insert their own flags" on public.question_flags;
drop policy if exists "Grown-ups flag as their kids" on public.question_flags;
create policy "Grown-ups flag as their kids"
  on public.question_flags for insert
  to authenticated
  with check (exists (select 1 from public.profiles p where p.id = profile_id and p.parent_id = auth.uid()));

-- 4) Sign-up: every new login is a grown-up. Agreeing on the sign-up form
--    (`consent_version` in the metadata) is stamped now; without it the app
--    asks before anyone plays. An app from before this still sends a birth
--    date and no consent: that login gets its first kid, as old accounts did.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_year    text := new.raw_user_meta_data ->> 'birth_year';
  v_month   text := new.raw_user_meta_data ->> 'birth_month';
  v_consent text := new.raw_user_meta_data ->> 'consent_version';
begin
  if v_consent !~ '^[A-Za-z0-9._-]{1,40}$' then
    v_consent := null;
  end if;
  insert into public.parents (id, consent_at, consent_version)
  values (new.id, case when v_consent is not null then now() end, v_consent)
  on conflict (id) do nothing;

  if v_year ~ '^\d{4}$' and v_month ~ '^\d{1,2}$' and v_month::int between 1 and 12 then
    insert into public.profiles (id, parent_id, birth_year, birth_month)
    values (new.id, new.id, v_year::smallint, v_month::smallint)
    on conflict (id) do nothing;
  end if;
  return new;
end;
$$;

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0012', 'parent_accounts', array[]::text[])
on conflict (version) do nothing;

-- ============================================================================
-- 0013_pins_and_kid_budget.sql
-- ============================================================================
-- Hazel Quest — PINs and a question budget per kid (#118)
-- Run in the Supabase SQL Editor (or `supabase db push`) after 0012.
-- Re-runnable, like every migration (see CLAUDE.md → migrations rules).
--
-- The owner's calls (2026-10-10): every kid opens their profile with a
-- 4-digit PIN (replacing 0012's secret picture); 👪 Grown-ups opens with the
-- grown-up's own PIN or their password; the question budget is per kid.
--
-- PINs are stored hashed (bcrypt, pgcrypto) in tables no client can read or
-- write; the app sets and checks them only through the functions below, which
-- also check the kid is the caller's.

-- pgcrypto: already in `extensions` on Supabase; created here for plain Postgres (CI).
create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- 1) Kid PINs.
create table if not exists public.kid_pins (
  profile_id uuid        primary key references public.profiles (id) on delete cascade,
  pin_hash   text        not null,
  updated_at timestamptz not null default now()
);
-- RLS on and no policies, no grants: only the security-definer functions get in.
alter table public.kid_pins enable row level security;
revoke all on public.kid_pins from anon, authenticated;

-- What the app may know: whether a kid has a PIN (not the PIN).
alter table public.profiles add column if not exists has_pin boolean not null default false;

-- The secret picture is replaced by the PIN.
alter table public.profiles drop column if exists picture_password;

create or replace function public.set_kid_pin(p_kid uuid, p_pin text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_pin is null or p_pin !~ '^\d{4}$' then
    raise exception 'pin_format: a PIN is 4 digits';
  end if;
  if not exists (select 1 from public.profiles where id = p_kid and parent_id = auth.uid()) then
    raise exception 'not_your_kid: that player belongs to another account';
  end if;
  insert into public.kid_pins (profile_id, pin_hash)
  values (p_kid, extensions.crypt(p_pin, extensions.gen_salt('bf')))
  on conflict (profile_id) do update set pin_hash = excluded.pin_hash, updated_at = now();
  update public.profiles set has_pin = true where id = p_kid;
end;
$$;

create or replace function public.check_kid_pin(p_kid uuid, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
      from public.kid_pins k
      join public.profiles p on p.id = k.profile_id
     where k.profile_id = p_kid
       and p.parent_id = auth.uid()
       and k.pin_hash = extensions.crypt(p_pin, k.pin_hash)
  );
$$;

-- 2) The grown-up's own PIN (optional: their password always works too).
create table if not exists public.parent_pins (
  id         uuid        primary key references auth.users (id) on delete cascade,
  pin_hash   text        not null,
  updated_at timestamptz not null default now()
);
alter table public.parent_pins enable row level security;
revoke all on public.parent_pins from anon, authenticated;

-- Readable by the grown-up (`parents` has no update grant, so only
-- set_parent_pin changes it).
alter table public.parents add column if not exists has_pin boolean not null default false;

create or replace function public.set_parent_pin(p_pin text)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if p_pin is null or p_pin !~ '^\d{4}$' then
    raise exception 'pin_format: a PIN is 4 digits';
  end if;
  insert into public.parent_pins (id, pin_hash)
  values (auth.uid(), extensions.crypt(p_pin, extensions.gen_salt('bf')))
  on conflict (id) do update set pin_hash = excluded.pin_hash, updated_at = now();
  insert into public.parents (id, has_pin) values (auth.uid(), true)
  on conflict (id) do update set has_pin = true;
end;
$$;

create or replace function public.check_parent_pin(p_pin text)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.parent_pins
     where id = auth.uid() and pin_hash = extensions.crypt(p_pin, pin_hash)
  );
$$;

revoke execute on function public.set_kid_pin(uuid, text) from public, anon;
revoke execute on function public.check_kid_pin(uuid, text) from public, anon;
revoke execute on function public.set_parent_pin(text) from public, anon;
revoke execute on function public.check_parent_pin(text) from public, anon;
grant execute on function public.set_kid_pin(uuid, text) to authenticated;
grant execute on function public.check_kid_pin(uuid, text) to authenticated;
grant execute on function public.set_parent_pin(text) to authenticated;
grant execute on function public.check_parent_pin(text) to authenticated;

-- 3) The question budget is per kid: begin_question_request's p_profile is
--    now the kid's id (the edge function sends it). Requests point at the kid
--    and go when the kid is removed. NOT VALID: rows logged under a login
--    before this are left as they are (they age out of every window in a day).
alter table public.question_requests drop constraint if exists question_requests_profile_id_fkey;
alter table public.question_requests drop constraint if exists question_requests_kid_fkey;
alter table public.question_requests add constraint question_requests_kid_fkey
  foreign key (profile_id) references public.profiles (id) on delete cascade not valid;

-- A per-kid budget would grow with every kid added, so a family has at most 8.
create or replace function public.profiles_kid_limit()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  if (select count(*) from public.profiles where parent_id = new.parent_id) >= 8 then
    raise exception 'kid_limit: a family account can have up to 8 players';
  end if;
  return new;
end;
$$;

drop trigger if exists profiles_kid_limit on public.profiles;
create trigger profiles_kid_limit
  before insert on public.profiles
  for each row execute function public.profiles_kid_limit();

insert into supabase_migrations.schema_migrations (version, name, statements)
values ('0013', 'pins_and_kid_budget', array[]::text[])
on conflict (version) do nothing;

commit;

-- What's recorded now:
select version, name from supabase_migrations.schema_migrations order by version;
