// AUTO-GENERATED by tools/assets/build.py — do not edit by hand.
// Re-run `python3 tools/assets/build.py` after changing the art generator.
import type { SpriteDef } from './sprites';

export const GENERATED_SPRITES: Record<string, SpriteDef> = {
  "blaze": {
    "emoji": "🦁",
    "world": {
      "sheet": "/sprites/blaze/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/blaze/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "shield": {
    "emoji": "🐢",
    "world": {
      "sheet": "/sprites/shield/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/shield/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "nova": {
    "emoji": "🦅",
    "world": {
      "sheet": "/sprites/nova/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/nova/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "ember-egg": {
    "emoji": "🥚",
    "world": {
      "sheet": "/sprites/ember-egg/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/ember-egg/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "ember-hatchling": {
    "emoji": "🐣",
    "world": {
      "sheet": "/sprites/ember-hatchling/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/ember-hatchling/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "ember-whelp": {
    "emoji": "🦎",
    "world": {
      "sheet": "/sprites/ember-whelp/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/ember-whelp/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "ember-dragon": {
    "emoji": "🐉",
    "world": {
      "sheet": "/sprites/ember-dragon/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/ember-dragon/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "sum-slime": {
    "emoji": "🟦",
    "world": {
      "sheet": "/sprites/sum-slime/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/sum-slime/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "count-bat": {
    "emoji": "🦇",
    "world": {
      "sheet": "/sprites/count-bat/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/count-bat/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "sir-sumsalot": {
    "emoji": "🐉",
    "world": {
      "sheet": "/sprites/sir-sumsalot/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/sir-sumsalot/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "null-fiend": {
    "emoji": "👹",
    "world": {
      "sheet": "/sprites/null-fiend/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/null-fiend/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "spore-puff": {
    "emoji": "🍄",
    "world": {
      "sheet": "/sprites/spore-puff/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/spore-puff/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "static-jelly": {
    "emoji": "🪼",
    "world": {
      "sheet": "/sprites/static-jelly/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/static-jelly/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "comet-crab": {
    "emoji": "🦀",
    "world": {
      "sheet": "/sprites/comet-crab/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/comet-crab/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "smog-fiend": {
    "emoji": "🌫️",
    "world": {
      "sheet": "/sprites/smog-fiend/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/smog-fiend/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "bolt-mouse": {
    "emoji": "🐭",
    "world": {
      "sheet": "/sprites/bolt-mouse/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/bolt-mouse/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "scrap-golem": {
    "emoji": "🗿",
    "world": {
      "sheet": "/sprites/scrap-golem/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/scrap-golem/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "gear-wyrm": {
    "emoji": "🐍",
    "world": {
      "sheet": "/sprites/gear-wyrm/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/gear-wyrm/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "rust-fiend": {
    "emoji": "🤖",
    "world": {
      "sheet": "/sprites/rust-fiend/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/rust-fiend/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "doodle-imp": {
    "emoji": "👻",
    "world": {
      "sheet": "/sprites/doodle-imp/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/doodle-imp/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "off-key-bird": {
    "emoji": "🐦",
    "world": {
      "sheet": "/sprites/off-key-bird/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/off-key-bird/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "pixel-witch": {
    "emoji": "🦹",
    "world": {
      "sheet": "/sprites/pixel-witch/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/pixel-witch/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "gray-fiend": {
    "emoji": "🌑",
    "world": {
      "sheet": "/sprites/gray-fiend/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/gray-fiend/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "mossback-cub": {
    "emoji": "🐻",
    "world": {
      "sheet": "/sprites/mossback-cub/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/mossback-cub/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "thornhare": {
    "emoji": "🐰",
    "world": {
      "sheet": "/sprites/thornhare/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/thornhare/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "grumblebee": {
    "emoji": "🐝",
    "world": {
      "sheet": "/sprites/grumblebee/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/grumblebee/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "thicket-warden": {
    "emoji": "🦌",
    "world": {
      "sheet": "/sprites/thicket-warden/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/thicket-warden/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "tide-sprite": {
    "emoji": "🌊",
    "world": {
      "sheet": "/sprites/tide-sprite/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/tide-sprite/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "meteor-mite": {
    "emoji": "☄️",
    "world": {
      "sheet": "/sprites/meteor-mite/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/meteor-mite/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "moon-moth": {
    "emoji": "🌙",
    "world": {
      "sheet": "/sprites/moon-moth/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/moon-moth/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "tide-colossus": {
    "emoji": "🐳",
    "world": {
      "sheet": "/sprites/tide-colossus/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/tide-colossus/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "cog-sprite": {
    "emoji": "⚙️",
    "world": {
      "sheet": "/sprites/cog-sprite/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/cog-sprite/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "hourglass-imp": {
    "emoji": "⏳",
    "world": {
      "sheet": "/sprites/hourglass-imp/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/hourglass-imp/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "relic-golem": {
    "emoji": "🗿",
    "world": {
      "sheet": "/sprites/relic-golem/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/relic-golem/battle.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "umbra": {
    "emoji": "🌑",
    "world": {
      "sheet": "/sprites/umbra/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/umbra/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "clockwork-titan": {
    "emoji": "🦾",
    "world": {
      "sheet": "/sprites/clockwork-titan/world.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    },
    "battle": {
      "sheet": "/sprites/clockwork-titan/battle.png",
      "frameW": 48,
      "frameH": 48,
      "frames": 7,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "attack": {
          "from": 2,
          "to": 4,
          "fps": 9,
          "loop": false
        },
        "hurt": {
          "from": 5,
          "to": 6,
          "fps": 7,
          "loop": false
        }
      }
    }
  },
  "elder-lumen": {
    "emoji": "👴",
    "world": {
      "sheet": "/sprites/elder-lumen/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "hub-kid": {
    "emoji": "🧒",
    "world": {
      "sheet": "/sprites/hub-kid/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "hub-innkeeper": {
    "emoji": "👩‍🍳",
    "world": {
      "sheet": "/sprites/hub-innkeeper/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "hub-librarian": {
    "emoji": "🦉",
    "world": {
      "sheet": "/sprites/hub-librarian/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "hub-merchant": {
    "emoji": "🦝",
    "world": {
      "sheet": "/sprites/hub-merchant/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "sage-abacus": {
    "emoji": "🧙",
    "world": {
      "sheet": "/sprites/sage-abacus/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "numbria-villager": {
    "emoji": "👧",
    "world": {
      "sheet": "/sprites/numbria-villager/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "numbria-merchant": {
    "emoji": "🦊",
    "world": {
      "sheet": "/sprites/numbria-merchant/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "sage-flora": {
    "emoji": "🧝",
    "world": {
      "sheet": "/sprites/sage-flora/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "verdara-villager": {
    "emoji": "👦",
    "world": {
      "sheet": "/sprites/verdara-villager/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "verdara-merchant": {
    "emoji": "🐸",
    "world": {
      "sheet": "/sprites/verdara-merchant/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "sage-cog": {
    "emoji": "🧑‍🔧",
    "world": {
      "sheet": "/sprites/sage-cog/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "gearfall-villager": {
    "emoji": "👷",
    "world": {
      "sheet": "/sprites/gearfall-villager/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "gearfall-merchant": {
    "emoji": "🐹",
    "world": {
      "sheet": "/sprites/gearfall-merchant/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "sage-muse": {
    "emoji": "🧚",
    "world": {
      "sheet": "/sprites/sage-muse/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "chromaria-villager": {
    "emoji": "🧑‍🎨",
    "world": {
      "sheet": "/sprites/chromaria-villager/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "chromaria-merchant": {
    "emoji": "🐙",
    "world": {
      "sheet": "/sprites/chromaria-merchant/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "village-shopkeeper": {
    "emoji": "🧑‍💼",
    "world": {
      "sheet": "/sprites/village-shopkeeper/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "village-elder": {
    "emoji": "👵",
    "world": {
      "sheet": "/sprites/village-elder/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "village-friend": {
    "emoji": "🧑",
    "world": {
      "sheet": "/sprites/village-friend/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "village-keeper": {
    "emoji": "🧓",
    "world": {
      "sheet": "/sprites/village-keeper/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "woods-hermit": {
    "emoji": "🧙‍♀️",
    "world": {
      "sheet": "/sprites/woods-hermit/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "woods-sprite": {
    "emoji": "🧚",
    "world": {
      "sheet": "/sprites/woods-sprite/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "woods-warden-sign": {
    "emoji": "🦡",
    "world": {
      "sheet": "/sprites/woods-warden-sign/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "coast-fisher": {
    "emoji": "🎣",
    "world": {
      "sheet": "/sprites/coast-fisher/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "coast-stargazer": {
    "emoji": "🔭",
    "world": {
      "sheet": "/sprites/coast-stargazer/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "coast-warden-sign": {
    "emoji": "🦭",
    "world": {
      "sheet": "/sprites/coast-warden-sign/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "depths-tinker": {
    "emoji": "🐭",
    "world": {
      "sheet": "/sprites/depths-tinker/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "depths-echo": {
    "emoji": "🤖",
    "world": {
      "sheet": "/sprites/depths-echo/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "depths-warden-sign": {
    "emoji": "🔧",
    "world": {
      "sheet": "/sprites/depths-warden-sign/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "spire-keeper": {
    "emoji": "🔮",
    "world": {
      "sheet": "/sprites/spire-keeper/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "grove-guardian": {
    "emoji": "🌙",
    "world": {
      "sheet": "/sprites/grove-guardian/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "grove-firefly": {
    "emoji": "🦋",
    "world": {
      "sheet": "/sprites/grove-firefly/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  },
  "grove-otter": {
    "emoji": "🦦",
    "world": {
      "sheet": "/sprites/grove-otter/world.png",
      "frameW": 32,
      "frameH": 32,
      "frames": 18,
      "anims": {
        "idle": {
          "from": 0,
          "to": 1,
          "fps": 3
        },
        "walk": {
          "from": 2,
          "to": 5,
          "fps": 8
        },
        "idleDown": {
          "from": 6,
          "to": 7,
          "fps": 3
        },
        "walkDown": {
          "from": 8,
          "to": 11,
          "fps": 8
        },
        "idleUp": {
          "from": 12,
          "to": 13,
          "fps": 3
        },
        "walkUp": {
          "from": 14,
          "to": 17,
          "fps": 8
        }
      }
    }
  }
};
