import type { ZoneId } from './zones';

/**
 * 16-bit environment art (generated by `tools/assets/tiles.py`).
 *
 * Every zone has one tileset strip at `/tiles/<zoneId>.png` — 32×32 frames
 * (16px art shown 2×) laid out left→right as indexed by `TILE_FRAME`. Ground,
 * path and water are opaque; solid/deco/exit are transparent overlays drawn on
 * top of a ground tile. Shared props live in `/tiles/props.png`; the Spire
 * tower is a single 32×64 image.
 */
export const TILESET_FRAMES = 9;

export const TILE_FRAME = {
  ground: [0, 1, 2],
  path: 3,
  water: [4, 5],
  solid: 6,
  deco: 7,
  exit: 8,
} as const;

export const PROPS_FRAMES = 5;

export const PROP_FRAME = {
  crystal: [0, 1],
  chestClosed: 2,
  chestOpen: 3,
  gate: 4,
} as const;

export const tilesetSheet = (zoneId: ZoneId) => `/tiles/${zoneId}.png`;
export const PROPS_SHEET = '/tiles/props.png';
export const SPIRE_SHEET = '/tiles/spire.png';

/** KaPlay asset keys (namespaced away from character sprites). */
export const tilesetKey = (zoneId: ZoneId) => `t_${zoneId}`;
export const PROPS_KEY = 't_props';
export const SPIRE_KEY = 't_spire';

/** Per-zone 256×144 battle backdrop (generated alongside the tilesets). */
export const battleBackdrop = (zoneId: ZoneId) => `/backgrounds/${zoneId}.png`;

/**
 * Deterministic ground-variant pick so the speckle pattern doesn't visibly
 * repeat on a grid but stays identical every time a zone is drawn.
 */
export function groundVariant(x: number, y: number): number {
  const h = ((x * 73856093) ^ (y * 19349663)) >>> 0;
  // Mostly the plain variant, occasionally the busier ones.
  const r = h % 10;
  return TILE_FRAME.ground[r < 6 ? 0 : r < 8 ? 1 : 2];
}
