import { ROOF_COLORS, type BuildingStyle, type RoofColor, type ZoneId } from './zones';

/**
 * 16-bit environment art (generated by `tools/assets/tiles.py`).
 *
 * Every zone has one tileset strip at `/tiles/<zoneId>.png` — 32×32 frames
 * (16px art shown 2×) laid out left→right as indexed by `TILE_FRAME`. Ground,
 * path and water are opaque; solid/deco/exit are transparent overlays drawn on
 * top of a ground tile. Shared props live in `/tiles/props.png`; the Spire
 * tower is a single 32×64 image.
 */
export const TILESET_FRAMES = 9;

export const TILE_FRAME = {
  ground: [0, 1, 2],
  path: 3,
  water: [4, 5],
  solid: 6,
  deco: 7,
  exit: 8,
} as const;

export const PROPS_FRAMES = 5;

export const PROP_FRAME = {
  crystal: [0, 1],
  chestClosed: 2,
  chestOpen: 3,
  gate: 4,
} as const;

export const tilesetSheet = (zoneId: ZoneId) => `/tiles/${zoneId}.png`;
export const PROPS_SHEET = '/tiles/props.png';
export const SPIRE_SHEET = '/tiles/spire.png';

/** KaPlay asset keys (namespaced away from character sprites). */
export const tilesetKey = (zoneId: ZoneId) => `t_${zoneId}`;
/** Key/sheet for any named tileset (zones, or a Spire floor's `spire-<theme>`). */
export const namedTilesetKey = (name: string) => `t_${name}`;
export const namedTilesetSheet = (name: string) => `/tiles/${name}.png`;

/**
 * Spire floor props (#74): rune seals (glowing ×2 / broken), the stairs
 * (sealed / open) and Umbra's two-tile throne.
 */
export const SPIRE_PROPS_FRAMES = 7;
export const SPIRE_PROP_FRAME = {
  ward: [0, 1],
  wardBroken: 2,
  stairsSealed: 3,
  stairsOpen: 4,
  throne: [5, 6],
} as const;
export const SPIRE_PROPS_SHEET = '/tiles/spire-props.png';
export const SPIRE_PROPS_KEY = 't_spire_props';
export const PROPS_KEY = 't_props';
export const SPIRE_KEY = 't_spire';

/**
 * Buildings (#72, #73): one tile sheet per architecture style at
 * `/tiles/town-<style>.png` (all opaque except the signs, which hang over the
 * facade) and nine-slice roofs in `/tiles/roofs.png` — 9 frames per colour
 * (in `ROOF_COLORS` order), each TL T TR / L M R / BL B BR.
 */
export const TOWN_FRAMES = 16;
export const TOWN_FRAME = {
  wallTop: 0,
  facade: 1,
  facadeWindow: 2,
  door: 3,
  floor: 4,
  counter: 5,
  shelf: 6,
  table: 7,
  bed: 8,
  sign: { shop: 9, inn: 10, library: 11, house: 12, sage: 13, tools: 14, star: 15 },
} as const;
export const townSheet = (style: BuildingStyle) => `/tiles/town-${style}.png`;
export const townKey = (style: BuildingStyle) => `t_town_${style}`;

export const ROOF_FRAMES = ROOF_COLORS.length * 9;
export const ROOF_SHEET = '/tiles/roofs.png';
export const ROOF_KEY = 't_roofs';

/**
 * Nine-slice roof frame for cell (col,row) of a `cols`×`rows` roof.
 * Edge columns/rows pick the trim/ridge/eave slices; the rest are shingles.
 */
export function roofFrame(color: RoofColor, col: number, row: number, cols: number, rows: number): number {
  const sx = col === 0 ? 0 : col === cols - 1 ? 2 : 1;
  const sy = row === 0 ? 0 : row === rows - 1 ? 2 : 1;
  return ROOF_COLORS.indexOf(color) * 9 + sy * 3 + sx;
}

/** Per-zone 256×144 battle backdrop (generated alongside the tilesets). */
export const battleBackdrop = (zoneId: ZoneId) => `/backgrounds/${zoneId}.png`;

/**
 * Deterministic ground-variant pick so the speckle pattern doesn't visibly
 * repeat on a grid but stays identical every time a zone is drawn.
 */
export function groundVariant(x: number, y: number): number {
  const h = ((x * 73856093) ^ (y * 19349663)) >>> 0;
  // Mostly the plain variant, occasionally the busier ones.
  const r = h % 10;
  return TILE_FRAME.ground[r < 6 ? 0 : r < 8 ? 1 : 2];
}
