import { ROOF_COLORS, type BuildingStyle, type PlaceIcon, type RoofColor, type ZoneId } from './zones';

/**
 * 16-bit environment art (generated by `tools/assets/tiles.py`).
 *
 * Every zone has one tileset strip at `/tiles/<zoneId>.png` — 32×32 frames
 * (16px art shown 2×) laid out left→right as indexed by `TILE_FRAME`. Ground,
 * path and water are opaque; solid/deco/exit are transparent overlays drawn on
 * top of a ground tile. Shared props live in `/tiles/props.png`; the Spire
 * tower is a single 32×64 image.
 */
export const TILESET_FRAMES = 9;

export const TILE_FRAME = {
  ground: [0, 1, 2],
  path: 3,
  water: [4, 5],
  solid: 6,
  deco: 7,
  exit: 8,
} as const;

/** Water (and Spire pit) animation speed, frames per second. */
export const WATER_FPS = 2;

export const PROPS_FRAMES = 5;

export const PROP_FRAME = {
  crystal: [0, 1],
  chestClosed: 2,
  chestOpen: 3,
  gate: 4,
} as const;

export const tilesetSheet = (zoneId: ZoneId) => `/tiles/${zoneId}.png`;
export const PROPS_SHEET = '/tiles/props.png';
export const SPIRE_SHEET = '/tiles/spire.png';

/** KaPlay asset keys (namespaced away from character sprites). */
export const tilesetKey = (zoneId: ZoneId) => `t_${zoneId}`;
/** Key/sheet for any named tileset (zones, or a Spire floor's `spire-<theme>`). */
export const namedTilesetKey = (name: string) => `t_${name}`;
export const namedTilesetSheet = (name: string) => `/tiles/${name}.png`;

/**
 * Spire floor props (#74): rune seals (glowing ×2 / broken), the stairs
 * (sealed / open) and Umbra's two-tile throne.
 */
export const SPIRE_PROPS_FRAMES = 7;
export const SPIRE_PROP_FRAME = {
  ward: [0, 1],
  wardBroken: 2,
  stairsSealed: 3,
  stairsOpen: 4,
  throne: [5, 6],
} as const;
export const SPIRE_PROPS_SHEET = '/tiles/spire-props.png';
export const SPIRE_PROPS_KEY = 't_spire_props';
export const PROPS_KEY = 't_props';
export const SPIRE_KEY = 't_spire';

/**
 * Buildings (#72, #73): one tile sheet per architecture style at
 * `/tiles/town-<style>.png` (all opaque except the signs, which hang over the
 * facade) and nine-slice roofs in `/tiles/roofs.png` — 9 frames per colour
 * (in `ROOF_COLORS` order), each TL T TR / L M R / BL B BR.
 */
export const TOWN_FRAMES = 16;
export const TOWN_FRAME = {
  wallTop: 0,
  facade: 1,
  facadeWindow: 2,
  door: 3,
  floor: 4,
  counter: 5,
  shelf: 6,
  table: 7,
  bed: 8,
  sign: { shop: 9, inn: 10, library: 11, house: 12, sage: 13, tools: 14, star: 15 },
} as const;
export const townSheet = (style: BuildingStyle) => `/tiles/town-${style}.png`;
export const townKey = (style: BuildingStyle) => `t_town_${style}`;

export const ROOF_FRAMES = ROOF_COLORS.length * 9;
export const ROOF_SHEET = '/tiles/roofs.png';
export const ROOF_KEY = 't_roofs';

/**
 * Nine-slice roof frame for cell (col,row) of a `cols`×`rows` roof.
 * Edge columns/rows pick the trim/ridge/eave slices; the rest are shingles.
 */
export function roofFrame(color: RoofColor, col: number, row: number, cols: number, rows: number): number {
  const sx = col === 0 ? 0 : col === cols - 1 ? 2 : 1;
  const sy = row === 0 ? 0 : row === rows - 1 ? 2 : 1;
  return ROOF_COLORS.indexOf(color) * 9 + sy * 3 + sx;
}

/**
 * Overworld art (#75 Phase 1): `/tiles/overworld.png`, 32×32 frames — the
 * mountain overlay, the sand base, two fog frames (drifting), and one icon
 * per kind of place (the tower is the tall Spire sprite instead).
 */
export const OVERWORLD_FRAME = {
  mountain: 0,
  sand: 1,
  fog: [2, 3],
  icon: { town: 4, hamlet: 5, forest: 6, cave: 7, shrine: 8, coast: 9, grove: 10 } satisfies Record<
    Exclude<PlaceIcon, 'tower'>,
    number
  >,
} as const;
export const OVERWORLD_FRAMES = 11;
export const OVERWORLD_SHEET = '/tiles/overworld.png';
export const OVERWORLD_KEY = 't_overworld';

/**
 * Fog puffs (#75 item 7): `/tiles/fog-puffs.png`, three soft cloud shapes,
 * 48×48 each. A fog bank is drawn as many of them overlapping and drifting
 * around each other (`lib/fog.ts`), so its edges are round and wispy.
 */
export const FOG_PUFF_SHEET = '/tiles/fog-puffs.png';
export const FOG_PUFF_KEY = 't_fogpuffs';
export const FOG_PUFF_FRAMES = 3;
export const FOG_PUFF_SIZE = 48;

/**
 * Edge blending (#75, #71b): `/tiles/<zoneId>-blend.png`, 32×32 frames, 16 per
 * row. The renderer draws a tile centred on every corner where different
 * terrain meets, so coasts, beaches and roads come out rounded instead of
 * square (`blendLayer`, lib/terrain.ts). Classes stack low → high (water,
 * sand, ground, path); a class's shape at a corner is a mask of which of the
 * 4 cells around it reach that class (top-left 1, top-right 2, bottom-left 4,
 * bottom-right 8). Most corners hold two classes and draw one ready-made
 * opaque pair tile (`blendPairFrame`); a corner with three or four draws its
 * lowest pair, then the higher shapes (`blendShapeFrame`). Layout, as
 * `tools/assets/tiles.py` writes it: 0–44 shapes, 45–134 water pairs (two
 * water frames each), 135–179 land pairs.
 */
export const BLEND_COLS = 16;
export const BLEND_ROWS = 12;
export const BLEND_FRAMES = 180;
/** Terrain classes that blend, low → high: each draws over the ones below it. */
export const BLEND_CLASS = { water: 0, sand: 1, ground: 2, path: 3 } as const;
export type BlendClass = (typeof BLEND_CLASS)[keyof typeof BLEND_CLASS];
export type LandClass = Exclude<BlendClass, 0>;
/** A water pair's second water frame sits this many frames after its first. */
export const BLEND_WATER_STEP = 15;
const LAND_PAIRS = ['1-2', '1-3', '2-3'];

/** A land class's shape (with its darker rim) at a corner, drawn over land. */
export function blendShapeFrame(cls: LandClass, mask: number): number {
  return (cls - 1) * 15 + (mask - 1);
}

/**
 * A ready-made opaque corner: `lower` everywhere, `upper`'s shape (by `mask`)
 * on top — with a foam line when `lower` is water. For water this is the first
 * water frame; the second is `BLEND_WATER_STEP` frames on.
 */
export function blendPairFrame(lower: BlendClass, upper: LandClass, mask: number): number {
  // A wrong pair would silently draw another pair's tile — fail loudly instead.
  if (lower >= upper) throw new Error(`blendPairFrame: class ${lower} must be below class ${upper}`);
  if (lower === BLEND_CLASS.water) return 45 + (upper - 1) * 2 * 15 + (mask - 1);
  return 135 + LAND_PAIRS.indexOf(`${lower}-${upper}`) * 15 + (mask - 1);
}
export const blendSheet = (zoneId: ZoneId) => `/tiles/${zoneId}-blend.png`;
export const blendKey = (zoneId: ZoneId) => `t_${zoneId}_blend`;

/** Per-zone 256×144 battle backdrop (generated alongside the tilesets). */
export const battleBackdrop = (zoneId: ZoneId) => `/backgrounds/${zoneId}.png`;

/**
 * Deterministic ground-variant pick so the speckle pattern doesn't visibly
 * repeat on a grid but stays identical every time a zone is drawn.
 */
export function groundVariant(x: number, y: number): number {
  const h = ((x * 73856093) ^ (y * 19349663)) >>> 0;
  // Mostly the plain variant, occasionally the busier ones.
  const r = h % 10;
  return TILE_FRAME.ground[r < 6 ? 0 : r < 8 ? 1 : 2];
}
