"""
Regenerate every 16-bit asset the game ships:

    pip install pillow numpy lameenc
    python3 tools/assets/build.py            # from hazel-game/
    python3 tools/assets/build.py overworld  # only the #75 Phase 1 additions
    python3 tools/assets/build.py blend      # only the edge-blend sheets (#71b)
    python3 tools/assets/build.py signpost   # only the signpost prop (#75 item 6)
    python3 tools/assets/build.py fog        # only the fog-puff sheet (#75 item 7)

Writes public/sprites/**, public/tiles/**, public/backgrounds/**,
public/audio/16bit/** and the sprite manifest src/content/sprites.generated.ts.
Output is deterministic — re-running produces the same files.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import audio  # noqa: E402
import build_sprites  # noqa: E402
import tiles  # noqa: E402

ROOT = HERE.parent.parent  # hazel-game/
PUBLIC = ROOT / 'public'
MANIFEST = ROOT / 'src' / 'content' / 'sprites.generated.ts'


def write_manifest(data: dict):
    body = json.dumps(data, indent=2, ensure_ascii=False)
    MANIFEST.write_text(
        '// AUTO-GENERATED by tools/assets/build.py — do not edit by hand.\n'
        '// Re-run `python3 tools/assets/build.py` after changing the art generator.\n'
        "import type { SpriteDef } from './sprites';\n\n"
        f'export const GENERATED_SPRITES: Record<string, SpriteDef> = {body};\n'
    )


def main():
    only = set(sys.argv[1:]) or {'sprites', 'tiles', 'audio'}
    if 'blend' in only:
        # Just the edge-blend sheets (#75 / #71b) — existing files untouched.
        tiles.build_blend(PUBLIC)
        print('blend ✓')
        return
    if 'fog' in only:
        # Just the fog puffs (#75 item 7) — existing files untouched.
        tiles.build_fog(PUBLIC)
        print('fog ✓')
        return
    if 'signpost' in only:
        # Just the wayfinding signpost (#75 item 6) — existing files untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'signpost'}))
        print('signpost ✓')
        return
    if 'overworld' in only:
        # Just the Phase 1 overworld additions (#75) — existing files untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'dawnreach-scout', 'shrine-keeper'}))
        tiles.build_overworld(PUBLIC)
        audio.build_music(PUBLIC, ['town', 'cave', 'shrine'])
        print('overworld ✓')
        return
    if 'sprites' in only:
        write_manifest(build_sprites.build(PUBLIC))
        print('sprites ✓')
    if 'tiles' in only:
        tiles.build(PUBLIC)
        print('tiles + backdrops ✓')
    if 'audio' in only:
        audio.build(PUBLIC)
        print('audio ✓')


if __name__ == '__main__':
    main()
