"""
Regenerate every 16-bit asset the game ships:

    pip install pillow numpy lameenc
    python3 tools/assets/build.py            # from hazel-game/
    python3 tools/assets/build.py overworld  # only the #75 Phase 1 additions
    python3 tools/assets/build.py blend      # only the edge-blend sheets (#71b)
    python3 tools/assets/build.py signpost   # only the signpost prop (#75 item 6)
    python3 tools/assets/build.py fog        # only the fog-puff sheet (#75 item 7)
    python3 tools/assets/build.py spells     # only the field-spell places + keepers (#75 item 9)
    python3 tools/assets/build.py dungeon    # only the Depths' lower floors + the stairs (#75 item 10)
    python3 tools/assets/build.py inns       # only the innkeepers + travelers (#75 item 11)
    python3 tools/assets/build.py sea        # only the Silver Shallows, the boat and the dock (#75 item 14)
    python3 tools/assets/build.py quests     # only Hermit Moss (#75 item 13)
    python3 tools/assets/build.py seamusic   # only the sea music: sailing, the Shallows, the fogbank (#75 item 14)
    python3 tools/assets/build.py lighthouse # only Gull Rock's lighthouse tower (#75 item 14)

Writes public/sprites/**, public/tiles/**, public/backgrounds/**,
public/audio/16bit/** and the sprite manifest src/content/sprites.generated.ts.
Output is deterministic — re-running produces the same files.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import audio  # noqa: E402
import build_sprites  # noqa: E402
import tiles  # noqa: E402

ROOT = HERE.parent.parent  # hazel-game/
PUBLIC = ROOT / 'public'
MANIFEST = ROOT / 'src' / 'content' / 'sprites.generated.ts'


def write_manifest(data: dict):
    body = json.dumps(data, indent=2, ensure_ascii=False)
    MANIFEST.write_text(
        '// AUTO-GENERATED by tools/assets/build.py — do not edit by hand.\n'
        '// Re-run `python3 tools/assets/build.py` after changing the art generator.\n'
        "import type { SpriteDef } from './sprites';\n\n"
        f'export const GENERATED_SPRITES: Record<string, SpriteDef> = {body};\n'
    )


def main():
    only = set(sys.argv[1:]) or {'sprites', 'tiles', 'audio'}
    if 'blend' in only:
        # Just the edge-blend sheets (#75 / #71b) — existing files untouched.
        tiles.build_blend(PUBLIC)
        print('blend ✓')
        return
    if 'fog' in only:
        # Just the fog puffs (#75 item 7) — existing files untouched.
        tiles.build_fog(PUBLIC)
        print('fog ✓')
        return
    if 'signpost' in only:
        # Just the wayfinding signpost (#75 item 6) — existing files untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'signpost'}))
        print('signpost ✓')
        return
    if 'inns' in only:
        # Just the innkeepers and travelers (#75 item 11) — every other file untouched.
        write_manifest(build_sprites.build(PUBLIC, only={f'{t}-{r}' for t in ('numbria', 'verdara', 'gearfall', 'chromaria') for r in ('innkeeper', 'traveler')}))
        print('inns ✓')
        return
    if 'sea' in only:
        # Just the boat's additions (#75 item 14): the Shallows, the boat, the
        # overworld sheet with the dock appended — every other file untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'gull-lamplighter'}))
        tiles.build_sea(PUBLIC)
        print('sea ✓')
        return
    if 'hill' in only:
        # Just Remembrance Hill (#75 item 14e): its people, its tiles, the marble
        # town sheet and the overworld sheet with the hill icon appended —
        # every other file untouched.
        write_manifest(build_sprites.build(PUBLIC, only={
            'hill-keeper', 'hill-posy', 'hill-merchant', 'hill-innkeeper',
            'hill-traveler', 'hill-carver', 'hill-elder', 'hill-jam'}))
        tiles.build_hill(PUBLIC)
        print('hill ✓')
        return
    if 'lighthouse' in only:
        # Just Gull Rock's lighthouse tower (#75 item 14) — every other file untouched.
        tiles.build_lighthouse(PUBLIC)
        print('lighthouse ✓')
        return
    if 'seamusic' in only:
        # Just the sea music (#75 item 14) — every other file untouched.
        audio.build_sea_music(PUBLIC)
        print('sea music ✓')
        return
    if 'quests' in only:
        # Just Hermit Moss (#75 item 13) — every other file untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'dawnreach-hermit'}))
        print('quests ✓')
        return
    if 'dungeon' in only:
        # Just the Clockwork Depths' lower floors and the stairs (#75 item 10).
        tiles.build_dungeon(PUBLIC)
        print('dungeon ✓')
        return
    if 'spells' in only:
        # Just the field-spell places and their people (#75 item 9) — every
        # other file untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'wayfarer-keeper', 'quiet-keeper', 'mine-miner'}))
        tiles.build_spell_places(PUBLIC)
        print('spells ✓')
        return
    if 'icons' in only:
        # Just the overworld sheet, now with the crystal regions' icons (#75
        # item 8) — existing frames unchanged, every other file untouched.
        tiles.build_overworld_sheet(PUBLIC)
        print('icons ✓')
        return
    if 'overworld' in only:
        # Just the Phase 1 overworld additions (#75) — existing files untouched.
        write_manifest(build_sprites.build(PUBLIC, only={'dawnreach-scout', 'shrine-keeper'}))
        tiles.build_overworld(PUBLIC)
        audio.build_music(PUBLIC, ['town', 'cave', 'shrine'])
        print('overworld ✓')
        return
    if 'sprites' in only:
        write_manifest(build_sprites.build(PUBLIC))
        print('sprites ✓')
    if 'tiles' in only:
        tiles.build(PUBLIC)
        print('tiles + backdrops ✓')
    if 'audio' in only:
        audio.build(PUBLIC)
        audio.build_sea_music(PUBLIC)
        print('audio ✓')


if __name__ == '__main__':
    main()
